### ISSUE TITLE
How to embed using gulp and webpack, always get createServer is undefined

### ISSUE THREAD

**Issue by nf3** [miragejs/miragejs#1003]
Hello, I'm new to miragejs and I'm not sure how to package it so that I can test it out in our development environment.  I see a cjs, esm, umd in the disti folder.  But each one throws some other kind of error each time I add it as a <script> tag.

I have a simple JS file that contains a single Init function, but everytime the page loads, I always get a createServer is undefined error.

Here is the code

```
import { createServer } from "miragejs"

const mirageInit = () => {

  createServer({
    routes() {
      this.namespace = "api"

      this.get("/movies", () => {
        return {
          movies: [
            { id: 1, name: "Inception", year: 2010 },
            { id: 2, name: "Interstellar", year: 2014 },
            { id: 3, name: "Dunkirk", year: 2017 },
          ],
        }
      })
    },
  })
}

export default mirageInit;
```

**Comment by x4th** [comment]
Why would you add it as a `<script />` tag if you're using webpack? Can you please create a minimal reproduction of your environment on [CodeSandbox](https://codesandbox.io/)?

**Comment by nf3** [comment]
Update, this can be closed.  I was able to get webpack to create the correct js file by adding the above code as an entry point .js file and then webpack was able to find the miragejs import and do the correct packaging.
