### ISSUE TITLE
non-Mirage passthrough() requests execute but never resolve when the request is set to "await" 

### ISSUE THREAD

**Issue by waldoc89** [miragejs/miragejs#1018]
I managed to get miragejs working in parallel to other requests from my FE using the `this.passthrough()` like this: 
```
			this.passthrough("http://localhost:3002/**")
			this.namespace = "api"
			this.get("/testapi/helo", (schema, request) => {
				console.log(schema, request)
				console.log(request.requestHeaders)
				return {
					"name": "test",
					"interval": 1,
					"api": "http://172.20.0.7:8000/test"
				}
			})
```
my react FE is set to port 3000. 
Whenever I call any other non-mirage request (`await axios.post('http://localhost:3002/logs')` for example) I get it executed but the code doesn't continue to run after the api request.  
Whenever I removed the "await" it works, can anyone explain why it's blocking the response stack? and what's actually happening there

**Comment by taras** [comment]
@waldoc89 you might be getting an error which prevents the code executing past `await`. Can you try to wrap that await in a try catch block to see what error you get?

```js
try {
  await axios.post('http://localhost:3002/logs')
} catch (e) {
  console.log('post to logs error', e)
}
```

**Comment by waldoc89** [comment]
Hi thanks for the response. actually, it's already in a try{}catch{}. 
this is the full code part: 
```
// Create a mock server and update state store with it's existense for future references.
const create = (serverName) => async (dispatch) => {
    let newId = parseInt(Object.keys(_mockServers)) + 1 || 0
    _mockServers[newId] = mockImports[serverName]({ environment: "development" })
    try {
        dispatch({ 
            type: 'mockServer/addServer', 
            payload: {
                "id": newId, 
                "fullId": `mockserver_${newId}`,
                "connection": "mock",
                "name": serverName,
                "ready": true
            }
        })
        console.log('log create')
        await axios.post('http://localhost:3002/logs',{
            "device": "MockServer", 
            "ts": Date.now(),
            "status": "success",
            "data": "A new Mock Server is ready.", 
            "action": "create",
        })
        console.log('end log create')
        return newId
    } catch (err) {
        console.error("Server Creating Failed", err)
        return false
    }
}

```

and this is my console: 
![image](https://user-images.githubusercontent.com/94450080/151014195-de09f29a-1d48-48bc-930b-d437cff3ca87.png)
(i ran it more than once). 
As you can see in the console - It does run these requests successfully and adds the line to my log. but the `console.log('end log create')` doesn't run (and whatever I have afterward `return newId`).  
I had a thought that it might be a "timing" thing within MirageJS, I remembered reading in the docs that it's set by default to 400 and sets itself to 0 when running tests. I was thinking maybe there is something there that throttles the response. I tried setting the timing to 0 but this didn't do much. I tried setting "logging" to `false` too, from past experiences sometimes this stuff get things stuck. didn't resolve the problem. 

```
import { createServer } from "miragejs"
const apitest = ({ environment = "test" } = {}) => {
	let server = createServer({
		environment,
		routes() {
			this.logging = true
			this.timing = 0
			this.namespace = "/api"
			this.passthrough("http://localhost:3002/**")
			this.get("/apitest/helo", (schema, request) => {
				console.log(schema, request)
				return {
					"name": "test",
					"interval": 1,
					"api": "http://172.20.0.7:8000/test"
				}
			})
		},
	})
	return server
}
export {apitest}
```

**Comment by waldoc89** [comment]
The user @Yap Yee Qiang from MirageJS Discord channel responded that the problem was within the axios package. 
The 2 working options: 
1. Use the vanilla `fetch` method. 
2. Downgrade axios to 0.21.0 `npm install axios@0.21.0`.
