### ISSUE TITLE
How can i start the server with nodejs? 

### ISSUE THREAD

**Issue by YaYaPao** [miragejs/miragejs#1038]
Version: 0.1.43
My application with vite run at: localhost:7070

Mirage scripts just like:

```js
import { createServer } from 'miragejs'
createServer({
  routes() {
    this.get('/api/users', () => [
      { id: '1', name: 'Luke' },
      { id: '2', name: 'Leia' },
      { id: '3', name: 'Anakin' },
    ])
  },
})
```

When i place mirage scripts at `./src/main.tsx` and it can get response by requesting `http://localhost:7070/api/users`

But when i place mirage scripts at `./mirage/index.js` (outside the `src` directory, because i don't to bundle it)，and after i excute `node mirage/index.js`, request can't work! is there any way to make it work correctly?

Have a great day!

**Comment by YaYaPao** [comment]
> Yeah Mirage doesn't run in non-browser environments. It can work in node if you have something like jsdom running (like Jest has). But sadly today it doesn't work without that.

It's this mean i can't excute mirage scripts in Node.js runtime directly？

**Comment by IanVS** [comment]
Yes I believe so for now, although there is some work ongoing to decouple mirage from the interceptor library it uses (pretender), which would theoretically make it possible to use a node.js based interceptor.  But, that's a ways off in the future.
