### ISSUE TITLE
I simply can't use/config trackRequests anymore and I'm not sure why

### ISSUE THREAD

**Issue by richardnikolas** [miragejs/miragejs#1043]
I had to recreate my test environment and I was using `miragejs` just fine, tracking all requests and asserting what I needed. 
But, on this new test environment (using React), I keep getting the same freaking error. I'm using version `0.1.44`.

**Mirage: Error: You cannot modify Pretender's request tracking once the server is created**

My config is like this now: 

```javascript
export function makeServer() {
    return createServer({
        environment: "test",
        trackRequests: true,
        serializers: {
            application: ApplicationSerializer
        },
```

I've already tried removing the `environment`, removing the `trackRequests` as well (hoping it would track if it was a test environment), etc. But nothing works. 

And after removing the trackRequests from the configuration, I saw this on the `mirageServer` log:

![image](https://user-images.githubusercontent.com/20261986/170784892-4ec4acc8-fc8c-43f1-a7d6-743f43a5e79b.png)

Anyone with this problem as well? Please help :(

**Comment by IanVS** [comment]
@richardnikolas can you try using version 0.1.43?  It seems that https://github.com/miragejs/miragejs/pull/1036 may have caused some problems, and we might need to revert it.

**Comment by richardnikolas** [comment]
@IanVS I tried using 0.1.42 and didn't work as well (because that's the one I was using on my old project). But yeah, I can try 0.1.43 as well.

**Comment by IanVS** [comment]
>I tried using 0.1.42 and didn't work as well

Were you getting the same error, or a different one?

**Comment by richardnikolas** [comment]
> Were you getting the same error, or a different one?

I was getting the same exact error.

**Comment by richardnikolas** [comment]
Sorry, @IanVS . I was using `^0.1.42` on my package.json 😑, so it was installing the newer version anyway. 
But now the tracking is working again with the _real_ `0.1.42`.

**Comment by cah-briangantzler** [comment]
Thanks for reporting. Have released a fix. I turned on trackedRequests in my app and all tests ran. I debugged a few of the tests and verified there were requests captured in `this.server.pretender.handledRequests`

**Comment by IanVS** [comment]
The fix hasn't been released just yet, but I'll try to get it out ASAP.

**Comment by cah-briangantzler** [comment]
Thanks so much for the release. Although I dont use the trackRequests, I have updated my app to 0.1.45 and all tests ran successfully.
