### ISSUE TITLE
Fetch-API requests seem to be skipped and only XMLHttp is being caught

### ISSUE THREAD

**Issue by waldemarennsaed** [miragejs/miragejs#1062]
## Description

I have implemented a simple mock server:

```typescript
import { createServer } from 'miragejs'

export function makeServer (environment: string = 'development') {
  console.debug('Starting mock server')
  let server = createServer({
    environment,

    routes: function () {
      this.logging = true
      this.urlPrefix = 'https://my-api.com'
      this.namespace = '/'

      this.passthrough(request => {
        console.debug('passthrough', request.url)
        return request.url.startsWith(`${import.meta.env.VITE_EXTERNAL_API_URL}`) || request.url.startsWith(`${import.meta.env.VITE_OAUTH_PROVIDER}`)
      });

      this.get('company', () => {
        console.debug('Handling GET company')
        const companiesResponse = [{
          address: 'Some address',
          avatar_url: 'https://some-image-server.com/my-company-image.png',
          description: 'The company',
          name: 'Company INC',
          phone: '+49 30 555 555 555',
          id: 1
        }]

        return companiesResponse
      })
    }
  })

  return server
}
```

My setup is consisting out of the following XHR:

* OIDC requests (e.g. GET https://my-auth-provider.com/realm/master/token) (using [oidc-client-ts](https://github.com/authts/oidc-client-ts) **which is using XMLHttp requests**
* API requests (using a custom generated package by the use of [swagger-codegen](https://github.com/swagger-api/swagger-codegen) **which is using Fetch-API requests**

Project is based on:

* Vite 3.1.0
* Vue 3.2.37
* TypeScript 4.6.4
* **CORS is active for the used API services** - but that shouldn't matter if the requests are being intercepted correctly by miragejs

## Problem

In my console, I only get logged the XMLHttp requests. The Fetch-API requests are not even being caught in the passthrough-function ...

**Screenshot:**

![Bildschirmfoto 2022-10-11 um 17 58 48](https://user-images.githubusercontent.com/94853611/195142127-37db8b4d-0d91-4f10-aed3-5247b64ae731.png)

But the network clearly shows that my fetch requests are also being executed:

![Bildschirmfoto 2022-10-11 um 18 02 46](https://user-images.githubusercontent.com/94853611/195142511-809c4d6d-a1ce-45a0-a6a8-9e637102b568.png)

---
Any ideas?

_Note: In the source-code of the miragejs project I could only find TS types for XMLHttp, nothing for fetch. Do we have support for the fetch-API? At least, the documentation says that both should work._

**Comment by cah-brian-gantzler** [comment]
I believe pretender looks at first come first serve, try moving the passthrough definition below (should be last) defined. 

While it doesnt specifically say it, the example does show it last https://miragejs.com/docs/getting-started/overview/#passthrough

**Comment by waldemarennsaed** [comment]
> I believe pretender looks at first come first serve, try moving the passthrough definition below (should be last) defined.
> 
> While it doesnt specifically say it, the example does show it last https://miragejs.com/docs/getting-started/overview/#passthrough

I already tried that but it didn't change anything - same behavior.

> I believe pretender looks at first come first serve, try moving the passthrough definition below (should be last) defined.

From reading the docs, I would have expected that both (also in a **mix**) should work. Unfortunately there is no setting to configure the API that is being intercepted by miragejs.

**Comment by waldemarennsaed** [comment]
## Update

I actually just removed the XHR requests so that only the fetch requests are being called - still the same behavior. It almost seems as if the fetch-interception is not working (or I have a huge misconfiguration somewhere - can't imagine since `mockServer.ts` is my only file using miragejs).

**Comment by cah-brian-gantzler** [comment]
What is the complete path for the company fetch appearing in your network tab. Looking to see if maybe there is a miss match on the host you have defined `https://my-api.com`

I also notice in all the docs (an my code) the requests have the / in them
```this.get('/company', () => {```

and the namespace does not end in / so maybe ```this.namespace = ''```    not setting it at all may be the same thing

There might be a problem in how the strings are being concatenated

I dont usually set host as the my api is on the same server that serves the web page.

**Comment by waldemarennsaed** [comment]
My host is http://localhost:5173 and my API is running on https://my-api.com

The final request-string is https://my-api.com/company - so I would expect it to be resolved correctly. Even with the following settings it's not working:

```typesccript
// this.urlPrefix = 'https://my-api.com'
// this.namespace = '/'

this.get('https://my-api.com/company', () => { // ... })
```

It's not even resolving for the full _exact_ path.

**Comment by waldemarennsaed** [comment]
## Update

Using a function to determine the passthrough is also not logging the fetch-requests at all:

```typescript
this.passthrough(request => {
        console.debug('Passthrough request', request.url)
        return true
      });
```

**Screenshot:**

![Bildschirmfoto 2022-10-11 um 19 46 07](https://user-images.githubusercontent.com/94853611/195163094-09745ec7-1786-41e5-b48a-867f89ca1a27.png)

`requesting comapanies` is being logged before the fetch happens - as you can see, it's the last console log. No more messages afterwards but the network request is being executed. So it really seems that miragejs is not intercepting that request at all.

**Comment by cah-brian-gantzler** [comment]
When you look at the network request that it NOT being caught, what is the verb? I am thinking its 'options` because thats what a pre-flight request uses.  

Just wondering if the pre-flight portion is tripping pretender up

**Comment by waldemarennsaed** [comment]
> When you look at the network request that it NOT being caught, what is the verb? I am thinking its 'options` because thats what a pre-flight request uses.
> 
> Just wondering if the pre-flight portion is tripping pretender up

Exactly, its a CORS request, which means that a preflight (`HTTP OPTIONS`) request is being made before the actual `HTTP GET `.

According to [this ticket on mirage/ember-cli-mirage](https://github.com/miragejs/ember-cli-mirage/issues/19), CORS should be available in my assumption - or am I wrong? I mean isn't this what the `passthrough` is exactly for?

**Comment by waldemarennsaed** [comment]
## Resolved

I was wondering about the following scenario:

Applying a custom, native fetch-request into my application (not using any swagger-codegen generated client-API), resolved in miragejs catching those fetch-requests that I do by just using the native fetch-API.

The fetch-requests from the API-packages, were not caught. Inspecting the client-APIs and their types, they provide the option for passing a fetch API. Further inspection of my API-packages, resolved into the following insights:

* package A was using `portable-fetch` as a dependency
* package B was using `isomorphic-fetch` as a dependendy

## Solution

Configuring those consumed API-packages A & B to using the `globalThis.fetch` or `window.fetch` (or just `fetch`), resolved the issue. Now those requests of those packages are being intercepted correctly by miragejs.

Thanks for all the support and quick resposes @cah-brian-gantzler !

**Comment by cah-brian-gantzler** [comment]
Glad to hear you solved it. Im only familiar with the native fetch, didnt know about the others.  Given that pretender replaces the native fetch, I wonder if there was something with those it didnt understand. 

Note: There is also the alpha option of using MSW https://mswjs.io/docs/ instead of pretender with mirage. Let me know if you want to try that out. Assume that would have worked with your previous code as the intercept point is in a different place.

**Comment by waldemarennsaed** [comment]
> Note: There is also the alpha option of using MSW https://mswjs.io/docs/ instead of pretender with mirage. Let me know if you want to try that out. Assume that would have worked with your previous code as the intercept point is in a different place.

Thanks, just looked into MSWJS and it looks pretty nice. I am sure it should work with my code since it's intercepting on the outgoing network request on service-worker level.

I will post my results here after trying it out 🚀
