### ISSUE TITLE
0.1.46 breaks embedded records without `serializeIds: false`

### ISSUE THREAD

**Issue by kevinansfield** [miragejs/miragejs#1073]
We were unable to upgrade from 0.1.45 to 0.1.46 because the response output switched from arrays of embedded records to arrays of ids in the new version. We also saw relationships appear in the output that weren't there/not included previously.

`GET http://localhost:4200/ghost/api/admin/users/me/?include=roles`

0.1.45 output:
```
{
    users: [{
        ...
        roles: [{id: '1', ...}]
    }]
}
```

0.1.46 output:
```
{
    users: [{
        ...
        roles: ['1'],
        posts: ['1', '2', '3']
    }]
}
```

I haven't had a chance to dig into it properly yet but from a cursory reading of the changes in the release I think it's likely due to the removal of the [early return for embedded models here](https://github.com/miragejs/miragejs/pull/850/files#diff-8e3d45dd0e9ec504195499d7fafe3efc08756c349fce602ef6538c593aa563d8L719-R718). Rather than immediately returning the attrs when an embedded model is serialized, it's now passed to `_maybeAddAssociationIds` which then overwrites the embedded records - that was confirmed by adding `serializeIds: false` to our application serializer which bypassed the `_maybeAddAssociationIds` logic and kept the embedded records in the output.

**Comment by IanVS** [comment]
@NoneOfMaster would you have a chance to take a look at this?
