### ISSUE TITLE
`timing` setting does not respect `environment: 'test'` without setting `testConfig`

### ISSUE THREAD

**Issue by rmjohnson-olo** [miragejs/miragejs#1079]
I was surprised to find out my mirage calls in my tests were taking over 400ms, even though I had my environment set to `test`. The `timing` [documentation](https://miragejs.com/api/classes/server/#timing) led me to believe setting the environment was the only thing necessary to get the 0ms delay. After some debugging I realized [this](https://github.com/miragejs/miragejs/blob/d26b777ee9bcd6ba6f4e89c9df6c509e54476c2b/lib/server.js#L288-L290) only gets called if I pass in a `testConfig` function. So adding in `testConfig: () => {}` fixed the problem. However, this feels unexpected and should probably either be changed or the documentation should be updated to make that more clear.

As well, I had expected an explicit setting of `timing: 0` would also work. Unfortunately because `0` is falsey, [this line](https://github.com/miragejs/miragejs/blob/4df48d6f6b961a7a640b275154e1b1833c764dd5/lib/mock-server/pretender-config.js#L222) ignores `0` and defaults to the `400`. I'd expect `0` to be a valid value for `timing` even if my environment wasn't `test`.

Let me know if I can help with any of this, more than happy to explain further or propose a PR.

**Comment by cah-brian-gantzler** [comment]
Please submit a PR. Looking at what you posted I would think that [this line](https://github.com/miragejs/miragejs/blob/4df48d6f6b961a7a640b275154e1b1833c764dd5/lib/mock-server/pretender-config.js#L222) would be where you would just fix it to understand 0.

You could just set the timing to 1 MS, would be about the same, update the docs accordingly

**Comment by rmjohnson-olo** [comment]
@cah-brian-gantzler, I've opened up the following PR to address both of these issues: https://github.com/miragejs/miragejs/pull/1080
