### ISSUE TITLE
New Docs Proposal

### ISSUE THREAD

**Issue by emersonbottero** [miragejs/miragejs#1098]
Hi. 
I did the new docs for [mermaidjs](https://mermaid.js.org/#/).
Can I do the same for this lib?

And is it in another repo? Couldn't find it in this repo.

Thanks

**Comment by IanVS** [comment]
Thanks for the offer.  Are there particular shortcomings in the current docs that you would like to address?

**Comment by emersonbottero** [comment]
Nothing is particular now.. just to modernize it. (I miss the dark theme though.. 😅)
some features will be available for later improvements like code blocks and other options that comes with it.

P.S.: I see a lot of people using json files to mock the API return and would be nice to add an examples using those in the docs.

**Comment by IanVS** [comment]
Thanks for the offer, but we don't want to completely rebuild the docs for the project right now.  If you'd like to make smaller improvements to specific areas of the docs, I'd be happy to review PRs.  The code for the site is at https://github.com/miragejs/site.
