### ISSUE TITLE
Module resolution error on import

### ISSUE THREAD

**Issue by christinachimi** [miragejs/miragejs#1114]
Hi - I came across this library when trying to find a mocking solution for my React Native project that could go beyond Jest tests. It seems like a good fit, but I can't get it working based on the docs. When I 

```
import { createServer } from "miragejs"
```

I get the error `Unable to resolve "./dist/mirage-cjs.js" from "../../node_modules/miragejs/index.js"` on startup. Is more documentation needed on setting this library up?

**Comment by cah-brian-gantzler** [comment]
I would think that it would be just what is documented. Since you have a miragejs/index.js file I would assume you have the dist/mirage-cjs.js file as well, but have you checked your node_modules just to be sure?

**Comment by christinachimi** [comment]
I have, my `miragejs/dist` folder has a `mirage.cjs` file and a `mirage.mjs` file (and `.map` versions of both). It also has a `mirage-umd.cjs`. If I patch `index.js` to point to that umd file, the app is able to load, but it doesn't seem like mirage is working so I don't think that's the right solution.

**Comment by cah-brian-gantzler** [comment]
I hope there was just some types in that previous message and you meant to say it has a `mirage-cjs.js` file and not `mirage.cjs`.  The index is pointing to `mirage-cjs.js` but says it cant find it. If you didnt have a type and your file is indeed `mirage.cjs` then that would be a problem. Hoping someone on the board that knows more about the actual build would be able to help you.

**Comment by christinachimi** [comment]
No typos. The result of an ls on the dist folder is

mirage-umd.cjs mirage.cjs.map mirage.mjs.map
mirage.cjs     mirage.mjs

**Comment by cah-brian-gantzler** [comment]
What version are you using. Im using 0.1.48

My ls of dist is
```
mirage-cjs.js           mirage-cjs.js.map       mirage-esm.js           mirage-esm.js.map       mirage-umd.js
```

Should yours match mine? Or is there some build process that alters this because of some other build process? Sorry I am more familiar with the code than the build/packaging process, but I had thought your dist would look the same as mine.

**Comment by christinachimi** [comment]
Aha, I did not realize the latest release would be a beta version, can't believe I didn't catch that. That seems to resolve this problem, so I'll close this out. Thank you.

**Comment by IanVS** [comment]
Yeah, sorry, I made some fairly major changes in the latest release, so wanted to keep it as a beta for a bit until we know for sure there won't be other breaking changes needed.

Glad you got it figured out and it's working correctly now.
