### ISSUE TITLE
Alpha published as NPM "latest"

### ISSUE THREAD

**Issue by ef4** [miragejs/miragejs#1115]
0.2.0-alpha.2 is marked as a prerelease on GitHub, but on NPM is was published to the "latest" tag, which will be served by default to everyone. Was this intentional?

If not, I would recommend publishing an 0.1.49 with the same contents as 0.1.48 to the "latest" tag, and republish the alpha under the "alpha" tag.

**Comment by IanVS** [comment]
Whoops, thanks for the catch.  I'll take care of it tomorrow.

**Comment by nglaviano** [comment]
Hi, this seemed to have happened with `0.2.0-alpha.3` as well

**Comment by IanVS** [comment]
Thanks for the reminder, this is now fixed.  I used `npm dist-tag add miragejs@0.1.48 latest` to restore 0.1.48 as the "latest".
