### ISSUE TITLE
Unable to run Application Tests using Vue CLI + Cypress + Mirage

### ISSUE THREAD

**Issue by kubacode** [miragejs/miragejs#146]
Hey there!

I'm spinning up a new Vue app and wanted to use Mirage to mock out my API but I'm having issues getting the Application tests to run in Cypress.

If I start the Mirage server in my src/main.js file, I get a response and all works as expected.

If I start the Mirage server in my Cypress test (tests/e2e/specs/test.js), I get a 404 response so I don't think Mirage is intercepting the request as expected, but I can't figure out why.

I've put together a [repo](https://github.com/kubacode/mirage-vue-cypress) with the test from the [Our First Test](https://miragejs.com/docs/testing/application-tests#our-first-test) section of the Mirage documentation.

Would it be possible to get some assistance to figure out what's not working here? Hopefully I've just missed something simple!

**Comment by kubacode** [comment]
I’m brand new to Cyprus too so I’m not sure - looks like we might have the blind leading blind here!

I’ve just wired this up from Vue CLI, so I haven’t looked at any of the config options - I’ll do some research into this and let you know how I go.

**Comment by kubacode** [comment]
Ok a little more (hopefully helpful) info.

Using Vue CLI, Cypress tests are started using the `npm run test:e2e` command, which defers to the `vue-cli-service test:e2e` command.

The `vue-cli-service test:e2e` command in turn then runs two main commands:
- `serve` which kicks off a WebpackDevServer
- `cypress open` which kicks off the Cypress test runner

This then means the Vue app and cypress are indeed being run in different processes.

A bit of digging in the Cypress [docs](https://docs.cypress.io/guides/references/best-practices.html#Web-Servers) suggests this is the recommended way to run web servers, so I guess this is the way that all Cypress testing works.

Seeing as Mirage intercepts the XMLHttpRequest/fetch request at the javascript level, I'm guessing its not really feasible to start the server from within the Cypress test?

**Comment by samselikoff** [comment]
After poking around a bit I got this to work:

```js
cy.server()

cy.route('/api/movies', routeData => {
  return fetch(routeData.url, { method: routeData.method }).then(res=>res.json())
})
```

Getting ready for some travel atm but this basically uses `cy.route` to intercept http requests made by the app, and proxies them to Mirage via a new fetch request.

Need to do some more testing to get a generalized solution but this works for now! Need to also forward along request body for writes.

I think you want to keep the server in the Cypress test process so you can do `server.create()` in your tests.

I'll follow up back here when I get some more time but hopefully this gets you unstuck. Sorry the docs were incomplete on this, I swear I paired with someone and they just dropped `new Server()` into their Cypress test and it worked, maybe they had it configured differently.

**Comment by kubacode** [comment]
Seems like a great start, this has got me going on GETting data via Mirage, woohoo! Agree would be best to keep the server in the Cypress test process.

I have had a go at forwarding along the body for POST requests, but it doesn't look like `cy.route` allows you to access the body in the `routeData` and I can't see any other way to access the body.

Really appreciate the quick responses, enjoy your travel!

**Comment by samselikoff** [comment]
@kubacode Coming back around to this at the end of my day but I think something like this might work:

```
import { makeServer } from '../../../src/server'

Cypress.on('window:before:load', (win) => {
  win.XMLHttpRequest = window.XMLHttpRequest
})

let server

beforeEach(() => {
  server = makeServer('test')
})

afterEach(() => {
  server.shutdown()
})

it("shows the movies", function() {
  server.createList("movie", 10);

  cy.visit("/");
  cy.get("li.movie").should("have.length", 10);
});

it("can delete a movie", function() {
  server.createList("movie", 3);

  cy.visit("/");
  cy.contains('Delete 2').click()

  cy.get("li.movie").should("have.length", 2);
});
```

I'll need to come up with some more robust code for swapping out the XMLHttpRequest & fetch objects from the iframe's window, but this seems very promising! Working for all defined routes.

**Comment by kubacode** [comment]
Looking promising!

This does seem to kill all Mirage logging in Cypress, and also seems to do something strange with the connection to the Vue server. If I make a change to a source file, the change is detected and code is recompiled, but the Cypress doesn't hot reload the updated code/re-run tests...

**Comment by samselikoff** [comment]
Probably need to add some new passthroughs to help with that. 

For logging try server.logging = true, I’m not at my computer right now but I did see it working I thought.

**Comment by samselikoff** [comment]
Been playing around with this a bit more today, it seems to be happening in tests without Mirage running at all...

https://www.youtube.com/watch?v=LbGpcAKlo1M

Is this sorta what you're running into? (Looks like the actual tests are intercepting the socket HMR requests and not triggering a reload)

**Comment by kubacode** [comment]
Not quite what I'm seeing - with the `Cypress.on` XMLHttpRequest override, hot reloading (or according to my shocking typing Hotreaload 😣) source code doesn't work at all.

https://youtu.be/zjWHCbJ89JM

(Updates to the test code are picked up and are hot reloaded)

**Comment by samselikoff** [comment]
I gotcha.

Can you try adding `this.passthrough()` to the bottom of your `routes()`?

```js
routes() {
  this.namespace = 'api'
  this.resource('movie')

  this.passthrough()
}
```

**Comment by kubacode** [comment]
No change when adding `this.passthrough()`. I can totally live without hot reloading, but would be great if there was no loss to 'normal' functionality.

PS `server.logging = true` has added the logs back in, the logs were being suppressed as the server was started in the test environment - doh!

**Comment by samselikoff** [comment]
nah we'll figure it out :)

yep! `test` env tries to keep logs clean

**Comment by samselikoff** [comment]
Update: @ryanto and I are working on finishing the homepage for miragejs.com and "launching" the project. After that, getting this working is our #1 priority. (We believe in order to get the story right here we'll need Mirage running in node, but that's TBD.)

**Comment by samselikoff** [comment]
@kubacode Check it out – new solution for you to test out.

Here are the steps.

**Step 1: Register a new Cypress Command**

Add this to your `tests/e2e/support/commands.js` file:

```js
let mirageFunctions = [];

Cypress.on("window:before:load", win => {
  win.mirageFunctions = mirageFunctions;
  win.runCypressMirageFunctions = function() {
    win.mirageFunctions.forEach(f => f(win.server));
  };
});

afterEach(() => {
  mirageFunctions = [];

  cy.window({ log: false }).then(win => {
    if (win.server) {
      win.server.shutdown();
      win.server = null;
    }
  });
});

Cypress.Commands.add("mirage", userFunction => {
  cy.window().then(win => {
    if (win.server) {
      userFunction(win.server);
    } else {
      mirageFunctions.push(userFunction);
    }
  });
});
```

**Step 2: Start Mirage when Cypress is enabled**

In your Vue app's `main.js`, start Mirage and run any Mirage Cypress functions if `window.Cypress` is true.

Here's what our `main.js` looks like:

```js
import Vue from "vue";
import App from "./App.vue";
import { makeServer } from "./server";

if (process.env.NODE_ENV === "development") {
  window.server = makeServer();
} else if (window.Cypress) {
  window.server = makeServer("test");
  window.runCypressMirageFunctions();
}

Vue.config.productionTip = false;

new Vue({
  render: h => h(App)
}).$mount("#app");
```

The first `if` block starts Mirage in development, the second in Cypress.

**Step 3: Write some tests with Mirage!**

You can now use the `cy.mirage` Cypress command in your tests, to seed Mirage's db before your app boots up, and make assertions about it after:

```js
it("shows a message if there are no movies", function() {
  cy.visit("/");

  cy.get("[data-testid=loading]").should("exist");

  cy.contains("No movies").should("be.visible");
});

it("works with 5 movies", function() {
  cy.mirage(server => {
    server.createList("movie", 5);
  });

  cy.visit("/");

  cy.get('[data-testid="movie"]').should("have.length", 5);
});

it("can delete a movie", function() {
  cy.mirage(server => {
    server.create("movie");
  });

  cy.visit("/");
  cy.contains("Delete 1").click();

  cy.contains("No movies").should("be.visible");
  cy.mirage(server => {
    expect(server.db.movies.length).to.be.empty;
  });
});
```

---

Give it a shot and let me know how it goes!

**Comment by kubacode** [comment]
Hey @samselikoff, sorry I've been way off the radar, day job went a little crazy and I've been travelling.

I've followed the new guide up on the website and Cypress seems to be behaving 'normally' now. Thanks so much for taking your time to get this working!

**Comment by samselikoff** [comment]
Awesome, so glad to hear!

**Comment by danielquintero** [comment]
Hey @samselikoff, I have a similar issue this time with angular + cypress (Nx Monorepo setup). It seems like nx runs them in separate processes too. I am able to get things close to a working state following the docs, but when a request is intercepted and I return a response for it, cypress does not catch anything. 
Would appreciate any help :)

Angular's bootstrap file
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { Server, Response } from 'miragejs';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
	enableProdMode();
} else {
	if ((window as any).Cypress) {
		new Server({
			environment: 'test',
			routes() {
				// All other API requests will still pass through
				this.passthrough();
				this.urlPrefix = 'https://some-external-server.com';
				const methods = ['get', 'put', 'patch', 'post', 'delete'];
				methods.forEach(method => {
					this[method]('/api/*', async (schema, request) => {
						const [status, headers, body] = await (window as any).handleFromCypress(request);
						return new Response(status, headers, body);
					});
				});
			},
		});
	}
}

platformBrowserDynamic()
	.bootstrapModule(AppModule)
	.catch(err => console.error(err));
```

Mirage's Server
```
import { Server, Model, Registry, Response } from 'miragejs';
import Schema from 'miragejs/orm/schema';

import { UserFactory } from './models/user';

type AppRegistry = Registry<
	{ user: typeof Model },
	{
		/* factories can be defined here */
	}
>;
export type AppSchema = Schema<AppRegistry>;

export function makeServer({ environment = 'development' } = {}): Server {
	const server = new Server<AppRegistry>({
		logging: true,
		environment,
		models: {
			user: Model,
		},
		factories: {
			user: UserFactory,
		},
		seeds(_server: Server) {
			_server.create('user');
		},
		routes() {
			this.urlPrefix = 'https://some-external-server.com';
			this.namespace = 'api';
			this.post('/jwt/', () => new Response(400, { some: 'header' }, { errors: ['name cannot be blank'] }));
		},
	});

	return server;
}
```

Cypress support file
```
import './commands';

Cypress.on('window:before:load', win => {
	(win as any).handleFromCypress = function(request) {
		return fetch(request.url, {
			method: request.method,
			headers: request.requestHeaders,
			body: request.requestBody,
		}).then(res => {
			const content = res.headers.get['content-type'] === 'application/json' ? res.json() : res.text();
			return new Promise(resolve => {
				content.then(body => resolve([res.status, res.headers, body]));
			});
		});
	};
});
```

**Comment by samselikoff** [comment]
@danielquintero sorry you're running into this!

It looks like you did copy over both the urlPrefix and namespace, that was going to be my first question.

If you can upload a project that produces the issue, I'd be more than happy to take a look! Otherwise it's really hard to diagnose.

**Comment by danielquintero** [comment]
@samselikoff thanks for your time! I managed to get this to work. If you think it would be helpful to create a PR to provide some explanation/instructions on how to get this to work on angular + cypress I would gladly help (the only framework missing a section on the website docs is Angular, would be fair to include it right?).

**Comment by samselikoff** [comment]
Yes absolutely it would! And I would be extremely appreciative of your help!

There was a PR a few months ago for this but it went stale: https://github.com/miragejs/site/pull/232

I would love if you could open a new one, just give that one a glance and see if there's anything missing. I think there was some trouble with Angular back then due to our lack of Typescript support, but it sounds like everything's working now.

Really appreciate your help.

**Comment by danielquintero** [comment]
@samselikoff I had a look at the open PR and it looks good, however it only adds mirage for development purposes, when you want to have mirage + cypress the process is somewhat different. I will comment in that other issue and leave this one to rest.

**Comment by samselikoff** [comment]
I think a new PR would be good actually, one that's fresh + just focuses on Angular. No worries if you don't have time for it, if you want to just drop the code in an issue that would be helpful too!

**Comment by danielgek** [comment]
Sorry, just catching up now, couldn't touch on that pr meanwhile, @danielquintero as i said on the pr if you want to discuss your implementation ping mr on mirage discord ;) i would be more than happy to help 😉

**Comment by psbanka** [comment]
FWIW, I was unable to get the [official recipe](https://miragejs.com/quickstarts/cypress/#step-3-have-cypress-define-a-proxy-function-for-your-apps-api-requests) to work if I was using an external origin.

The official-recipe version is checked in [here](https://github.com/psbanka/cypress-and-mirage), which does not work.
The version which uses the above example is checked in [here](https://github.com/psbanka/cypress-and-mirage/tree/different-integration) which does work.
