### ISSUE TITLE
Can't get mirage to work when running cypress run

### ISSUE THREAD

**Issue by romansndlr** [miragejs/miragejs#213]
Hey all!

I've been integrating mirage into our react + cypress app.

Everything worked great when running ```cypress open``` (running the tests inside a real browser controlled by cypress) as long as I added this line at the top of my test file:

```javascript
Cypress.on('window:before:load', win => {
  win.XMLHttpRequest = window.XMLHttpRequest
})
```

But, when running the ```cypress run``` command, our tests run in an electron browser and it seems like mirage is unable to swap the xhr requests with the mirage routes.

Would it be possible to get some assistance in figuring out how to overcome this problem?
Thanks so much for this wonderful piece of software!

**Comment by samselikoff** [comment]
How's [the latest Cypress quickstart](https://miragejs.com/quickstarts/cypress/setup) working out for this one?

**Comment by romansndlr** [comment]
I'll check it out and let you know

**Comment by samselikoff** [comment]
Closing for now, can reopen if we still have issues!
