### ISSUE TITLE
Add delay to Model mutation methods

### ISSUE THREAD

**Issue by ZengLawrence** [miragejs/miragejs#226]
I want to test scenarios where database writes take longer than expected.  For example, after saving a piece of data, then navigate to a dashboard to view.  If writing to database takes a long time, the dashboard might not be able to retrieve the newly added data.  

If I use "timing" config, it only delay the response but writing to Mirage DB still happens in real time.  Can you add a timing config to db mutation methods e.g. create, update, save?

**Comment by ZengLawrence** [comment]
I found that you can use a Promise to accomplish this.  See below code snippets.

```javascript
function delayRouteHandler(routeHandler, delay) {
    return new Promise(resolve => {
      setTimeout(() => resolve(routeHandler())
      , delay);
    });
  };
```

You can use delayRouteHnadler in regular setup like such:
```javascript
      this.post("/movies", (schema, request) => {
        return delayRouteHandler(() => {
          const attrs = JSON.parse(request.requestBody);
          return schema.movies.create(attrs);
        }, 1000);  //delay db operation by 1 second
      });
```

**Comment by ryanto** [comment]
Yup, exactly! We use this pattern whenever we need to simulate a slow backend.

Sounds like you got the issue solved, so I'm going to close this. Feel free to reopen if there's anything else you think is needed.

**Comment by ZengLawrence** [comment]
No problem. Can you add an example in your doc?  I had to look through Pretender doc to figure that out.  It would make it easier for others.
