### ISSUE TITLE
Rest API with "data" as root for responses

### ISSUE THREAD

**Issue by MichaelKaufman-AgC** [miragejs/miragejs#252]
We use "data" as the root for REST responses (singular and plural), and will need Mirage.js to mirror this. Is there a config to accomplish this?

**Comment by MichaelKaufman-AgC** [comment]
I missed `keyForModel` and `keyForCollection` in serializer docs, closing this issue. 😄

**Comment by samselikoff** [comment]
@MichaelKaufman-AgC glad you found it! Is the `data` root for all responses? If so it might be easier to do it in the `serialize()` function.
