### ISSUE TITLE
Not able to test error states with Cypress

### ISSUE THREAD

**Issue by yugandhar-pathi** [miragejs/miragejs#282]
I have followed below link to setup miragejs with Cypress.

https://miragejs.com/quickstarts/cypress/setup 

Issue: Setup doesn't work for error responses.

When I add below code in my test.

```
  /* skipping this test for now becuase miragjs,
   doesn't return error response as expected. */
  server.del('/users/1', () => {
    return new Response(400, {}, { message: 'Invalid input' });
  });
```

I actually receive below response in my application code (My application is using plain `fetch` , no `axios`).

To my surprise response from fetch has status as `200` but has payload as my error response.

```
{"type":"default","status":200,"ok":true,"statusText":"OK","headers":{"map":{"content-type":"application/json"}},"url":"https://localhost:3030/stores/1","_bodyInit":"{\"message\":\"Invalid input\"}","_bodyText":"{\"message\":\"Invalid input\"}"}
```

Can someone help me to solve this, I am blocked.

**Comment by asantos00** [comment]
Hi there, can you confirm that you are only starting mirage through cypress? It can happen that your frontend has MirageJS server already running and starting it with cypress just starts another one, that can lead to problems.

Can you confirm that you have no other code initiating mirage besides cypress?

One other thing, the payload you pasted, is it from the same request? Because the url in it is `https://localhost:3030/stores/1` and on your config it is `/users/1`.

Not sure if it helps, but we have a demo app that has a mirage + cypress configuration running [here](https://github.com/miragejs/react-demo).

I think our [discord](https://discord.gg/pPsdsrn) is a better place to discuss this.

**Comment by asantos00** [comment]
Hi @yugandhar-pathi, thanks for reaching out on discord. It really seems that what is suggested on the website does not handle well errors, or at least it swallows status codes.

I'd suggest changing it to the following while we don't fix the documentation

```js
// cypress/support/index.js
Cypress.on("window:before:load", win => {
  win.handleFromCypress = function(request) {
    return fetch(request.url, {
      method: request.method,
      body: request.requestBody
    }).then(async (res) => {
      const body = res.headers.map["content-type"] === "application/json"
        ? await res.json()
        : '';

      return [res.status, res.headers, body];
    });
  };
});

// src/index.js  - or wherever your starting mirage on your app
  let cyServer = new Server({
    environment: "test",
    routes() {
      ["get", "put", "patch", "post", "delete"].forEach(method => {
        this[method]("/*", async (schema, request) => {
          return new Response(...await window.handleFromCypress(request));
        });
      });
    }
  });
  cyServer.logging = false
```

This should fix your problem

**Comment by yugandhar-pathi** [comment]
I just tested the above fix... `payload` for success response is disturbed.
I get below `payload` for success response. I am not sure why `status` and `statusText` are pushed to `payload`
```
{type: "default", status: 200, ok: true, statusText: "OK", headers: {…}, …}
```

**Comment by yugandhar-pathi** [comment]
@asantos00 Thanks a lot !! for your quick fix. Your fix just works great !!

**Comment by samselikoff** [comment]
Nice work @asantos00 👍 Not sure how we missed this because what's on the website definitely doesn't cover a lot of cases, but I think this will do the trick!

**Comment by ryanto** [comment]
Thanks for reporting this! And @asantos00 thank you so much for fixing it! 💪 

I've updated the guides on the website to match follow your example.

I'm going to close this, but feel free to reopen if you're still running into anything.

**Comment by Waxolunist** [comment]
What is `headers.map`? Doesn't exist on haders usually

**Comment by samselikoff** [comment]
@Waxolunist not sure, if you have a more specific question or issue you're facing probably best to open a new issue!

**Comment by gtsop-pf** [comment]
@ryanto would very much appreciate if you could provide some feedback on this. I've been skipping my error tests in hope of a workaround for quite a bit.

**Comment by gtsop-pf** [comment]
I dag through the debugger to see why mirage wouldn't pick up the status code. I realized that my code wouldn't use the `Response` object exported from `miragejs` even though I had an `import` statement. To make sure I'm using the correct object I did
```
import { Response as MResponse } from 'miragejs'
...
return MResponse(500,{}, {error: 'some error'});
```

![Screenshot from 2021-11-08 13-57-19](https://user-images.githubusercontent.com/90187915/140738052-a0666110-5e70-424d-b028-90ce1336f634.png)
.

**Comment by gtsop-pf** [comment]
Following up from my previous comment, I managed to get this working by keeping a reference of the Response class on Cypress and using that for my error codes. Here is my code:

<details>
<summary>cypress/support/index.js</summary>

```javascript
import './commands';

import { setupCypressPassthrough } from '../../src/mirage';

setupCypressPassthrough();
```
</details>

<details>
<summary>src/mirage/setup-cypress-passthrough.js</summary>

```javascript
import { makeServer } from './make-server';
import { Response } from 'miragejs';

export function setupCypressPassthrough() {
  // https://miragejs.com/quickstarts/cypress/#step-3-have-cypress-define-a-proxy-function-for-your-apps-api-requests
  Cypress.on('window:before:load', (win) => {
    win.handleFromCypress = function (request) {
      return fetch(request.url, {
        method: request.method,
        headers: request.requestHeaders,
        body: request.requestBody,
      }).then((res) => {
        let content = res.headers.get('content-type').includes('application/json')
          ? res.json()
          : res.text();
        return new Promise((resolve) => {
          content.then((body) => resolve([res.status, res.headers, body]));
        });
      });
    };
  });

  // https://miragejs.com/quickstarts/cypress/#step-5-write-tests-using-your-mirage-server
  let server;

  beforeEach(function () {
    server = makeServer({
      environment: 'development',
    });

    // provide server instance via `this.server` to test cases (`it` blocks)
    cy.wrap(server).as('server');

    cy.wrap(Response).as('Response');
  });

  afterEach(() => {
    server.shutdown();
  });
}
```
</details>

<details>
<summary>cypress/integration/home.spec.js</summary>

```javascript
describe('Pages | Home', function () {
  it("Shows an error message when shops won't load", function () {
    cy.visit('/');

    this.server.get('/api/user/stores', () => {
      return new this.Response(401, {}, { error: 'fail' });
    });
  });
});
```
</details>
