### ISSUE TITLE
Relationships not yielding results

### ISSUE THREAD

**Issue by dugajean** [miragejs/miragejs#284]
I have the following fake API:

```
import { Server, Model, Factory, belongsTo, hasMany } from 'miragejs'
import faker from 'faker'

new Server({
  models: {
    company: Model.extend({ jobs: hasMany() }),
    job: Model.extend({ company: belongsTo() })
  },

  routes() {
    this.namespace = 'api'

    this.get('/companies')
    this.get('/companies/:id')

    this.get('/jobs')
    this.get('/jobs/:id')
  },

  factories: {
    company: Factory.extend({
      name: faker.company.name,
      logo: faker.company.logo,
    }),

    job: Factory.extend({
      title: () => faker.name.jobTitle(),
      createdAt: () => faker.date.past(),
      location: () => `${faker.address.city()}, ${faker.address.country()}`,
      body: () => `${faker.lorem.paragraphs(3)}
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}
- ${faker.lorem.sentence()}

${faker.lorem.paragraphs(2)}
      `
    })
  },

  seeds(server) {
    server.createList('company', 5).forEach(company => server.createList('job', 10, { company }))
  }
})
```

When I do `GET /api/companies` I get one result back: `{ id: "1" }`. I'm expecting 5 companies back. Also when doing `GET /api/job/1?include=company` I never get the company back in the result, but I get the rest of the fake information.

Any idea what's going on here with my company model? It's simply not working.

**Comment by samselikoff** [comment]
First, it looks you're mocking out a JSON:API backend so I would use the [JSONAPISerializer](https://miragejs.com/api/classes/jsonapi-serializer):

```js
import { JSONAPISerializer } from 'miragejs'

new Server({
  serializers: {
    application: JSONAPISerializer
  }
})
```

Second, the response to `/api/companies` does seem wrong... first step in debugging these is to do a `server.db.dump()` right before your API call, and make sure the database looks as you expect. (Sometimes I do `window.server = server` to make this easy). Let me know what it says and I can help from there!

**Comment by dugajean** [comment]
@samselikoff Thanks on the advice for adding the serializer; That helped! Are there plans for a JSON LD serializer in the future?

For the information you requested, this is the output (the companies part):

```
companies: Array(5)
  0: {jobIds: Array(10), logo: undefined, name: undefined, id: "1"}
  1: {jobIds: Array(10), logo: undefined, name: undefined, id: "2"}
  2: {jobIds: Array(10), logo: undefined, name: undefined, id: "3"}
  3: {jobIds: Array(10), logo: undefined, name: undefined, id: "4"}
  4: {jobIds: Array(10), logo: undefined, name: undefined, id: "5"}
```

**Comment by dugajean** [comment]
I was using the faker.js API incorrectly. It's `companyName`, not `name`. Thanks for the help!

**Comment by samselikoff** [comment]
Awesome, glad you found it!

Haven't heard of JSON LD but if it's popular enough we can add it. For now if I was building a JSON LD app I'd probably make my own application serializer by extending the base `Serializer` or `RestSerializer` class, or even JSONAPISerializer (or copying it + changing what I need).

You can take a look at the source and see if you'd like to do that:

- [RestSerializer](https://github.com/miragejs/miragejs/blob/master/lib/serializers/rest-serializer.js)
- [JSONAPISerializer](https://github.com/miragejs/miragejs/blob/master/lib/serializers/json-api-serializer.js)
