### ISSUE TITLE
Allow to supress errors when a missing route is requested

### ISSUE THREAD

**Issue by julionav** [miragejs/miragejs#294]
I'm adding Mirage to an existing application to mock some of the backend endpoints as a compliment.

Currently, mirage logs an error when a route that hasn't been defined is requested, but since those routes actually exist in my backend I do not intend to mock them.

![](https://p-vvf5mjm.t2.n0.cdn.getcloudapp.com/items/llu4lWwW/Image+2020-01-28+at+12.47.14.png?v=141d987835d45361b6ae3c1c29372514)

**Comment by samselikoff** [comment]
In case someone else lands on this, how'd you solve it? Found the `passthrough()` api?
