### ISSUE TITLE
Back to the future 😄

### ISSUE THREAD

**Issue by ivan-dalmet** [miragejs/miragejs#296]
I think there is a little typo in the documentation 😉 

https://github.com/miragejs/miragejs/blob/f30ba5c6a5c28ac8b861287e82216c963ea09a6b/lib/serializer.js#L332

Still searching for the 0.2.2 😄

**Comment by samselikoff** [comment]
Hah! Definitely a hangover from very old ember-cli-mirage ^_^

Thanks! https://github.com/miragejs/miragejs/commit/58c86ae8e5bda5c8410c8fd944934070f8034b7c closes.
