### ISSUE TITLE
Doc: use `const` instead of `let` if value never reassigned in examples

### ISSUE THREAD

**Issue by zoltan-nz** [miragejs/miragejs#305]
Just a little cosmetics suggestion. TsLint alerts all the time if a value is declared with `let` instead of `const` if the value is never reassigned again. `eslint` rule can help and update code automatically: https://eslint.org/docs/rules/prefer-const

It is great to show best practices in the documentation, so if somebody will copy examples, they will learn nice patterns immediately. ;)

https://github.com/airbnb/javascript#references
https://google.github.io/styleguide/jsguide.html#features-use-const-and-let

**Comment by samselikoff** [comment]
I truly hate const :( that sucks tslint alerts about it...

**Comment by samselikoff** [comment]
I'm sure it's possible to configure the linter for this project's source? I don't think const vs. let is a hard best practice distinction and I don't think a linter rule should force us to update the entire codebase given its written with let.

**Comment by zoltan-nz** [comment]
> I truly hate const :( that sucks tslint alerts about it...

;) OK. I understand now what is the reason that I see only `let` in this codebase. ;)

**Comment by zoltan-nz** [comment]
> I'm sure it's possible to configure the linter for this project's source? I don't think const vs. let is a hard best practice distinction and I don't think a linter rule should force us to update the entire codebase given its written with let.

No worries. Anyway, TsLint runs on `ts` files only, so it doesn't have any effect on the main codebase. All fine.

**Comment by samselikoff** [comment]
Haha ok thanks for understanding
