### ISSUE TITLE
Usage with Axios

### ISSUE THREAD

**Issue by mcmillhj-wta** [miragejs/miragejs#307]
I think I am likely confused but wanted to ask here to get some clarification. Should Mirage be able to work with other HTTP libraries such as [axios](https://github.com/axios/axios)? 

I made a small test case using Jest + Create-React-App and Mirage doesn't seem to be intercepting the request:

```
// mirage.test.ts
import axios from "axios";
import { Server, Response } from "miragejs";

let server: any;
beforeEach(() => {
  server = new Server({
    routes() {
      this.namespace = "api";

      this.post("/resource", () => {
        return new Response(200, {}, "Success");
      });
    }
  });
});

afterEach(() => {
  server.shutdown();
});

it("can post a resource", async () => {
  await axios.post("/api/resource", JSON.stringify({ data: 1 }));
});
```

`npm run test -- mirage.test.ts`

```sh
 FAIL  mirage.test.ts
  ✕ can post a resource (73ms)

  ● can post a resource

    connect ECONNREFUSED 127.0.0.1:80



Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.172s, estimated 1s
Ran all test suites matching /mirage.test.ts/i.
```

However, if I switch to using `fetch`, the test passes:

```
it("can post a resource", async () => {
  await fetch("/api/resource", {
    method: "POST",
    body: JSON.stringify({ data: 1 })
  });
});
```

`npm run test -- mirage.test.ts`

```sh
 PASS  mirage.test.ts
  ✓ can post a resource (471ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.738s, estimated 2s
Ran all test suites matching /mirage.test.ts/i.

Active Filters: filename /mirage.test.ts/
 › Press c to clear filters.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press o to only run tests related to changed files.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.
  console.groupCollapsed node_modules/miragejs/dist/mirage-cjs.js:5946
      Mirage: [200] POST http://localhost:80/api/resource

  console.groupCollapsed node_modules/miragejs/dist/mirage-cjs.js:5965
        Response

  console.log node_modules/miragejs/dist/mirage-cjs.js:5966
        Success

  console.groupCollapsed node_modules/miragejs/dist/mirage-cjs.js:5968
        Request (data)

  console.log node_modules/miragejs/dist/mirage-cjs.js:5969
        { data: 1 }

  console.groupCollapsed node_modules/miragejs/dist/mirage-cjs.js:5971
        Request (raw)

  console.log node_modules/miragejs/dist/mirage-cjs.js:5972
        FakeRequest {
      _eventListeners: 
       { loadend: [ [Function] ],
         abort: [ [Function] ],
         load: [ [Function] ],
         progress: [ [Function] ],
         loadstart: [ [Function] ] },
      readyState: 4,
      requestHeaders: { 'content-type': 'text/plain;charset=UTF-8' },
      requestBody: '{"data":1}',
      status: 200,
      statusText: 'OK',
      upload: 
       { _eventListeners: 
          { loadend: [Array],
            abort: [Array],
            load: [Array],
            progress: [Array],
            loadstart: [Array] } },
      onload: [Function],
      onerror: [Function],
      ontimeout: [Function],
      onabort: [Function],
      method: 'POST',
      url: 'http://localhost:80/api/resource',
      async: true,
      username: undefined,
      password: undefined,
      responseText: 'Success',
      response: 'Success',
      responseXML: null,
      responseURL: 'http://localhost:80/api/resource',
      sendFlag: true,
      sendArguments: { '0': '{"data":1}' },
      errorFlag: false,
      params: {},
      queryParams: {},
      responseHeaders: { 'Content-Type': 'application/json' } }
```

Any advice or direction would be appreciated. The app I was trying to integrate Mirage into is quite large and uses `axios` pretty much everywhere.  I can also post a repo that reproduces this if needed.  

Thanks.

**Comment by vedovelli** [comment]
I am curious: is there a special reason to make an HTTP request from your tests?

Usually we let the component being tested do the request and then assert if the desired elements are present in the markup.

**Comment by mcmillhj-wta** [comment]
A lot of our test suite tests action creators that fire HTTP requests and update our Redux state accordingly so that is what I was trying to replicate with the small test above.

**Comment by samselikoff** [comment]
It definitely should, and lots of folks use Mirage to write exactly these sorts of tests. Will investigate!

**Comment by samselikoff** [comment]
@mcmillhj-wta if it's not too much to post the repo publicly that would help for sure! I have an idea of what's happening.

**Comment by mcmillhj-wta** [comment]
@samselikoff Weird, the repo I was using to attempt to re-create this is passing ... It must be something unique to my setup that is unrelated to MirageJS. I am going to close for now while I investigate.

**Comment by afvr94** [comment]
Hello @mcmillhj-wta did you find what was wrong? I am having the same problem in my tests. Thank you.

**Comment by mcmillhj-wta** [comment]
@afvr94 It turned out we had an [Axios intercepter](https://github.com/axios/axios#interceptors) somewhere in our project that was causing the issues.

**Comment by janeivind** [comment]
@samselikoff Just startet implementing miragejs, great stuff! Using axios and miragejs with my vue app, my code is working fine via browser, but i get a ECONNREFUSED 127.0.0.1:80 in my tests. The server setup file is imported to the tests, and I have console logged that the instance is set up i routes().

To isolate the problem, I endend up with a single test to bypass my setup.
{code}
import { Server, Model } from 'miragejs'
import axios from 'axios';
....
    it.only("routes config option works", async () => {
        server = new Server({
            environment: "test",
            models: {
                user: Model
            },
            routes() {
                this.namespace = "api";

                this.get("/users");
            }
        });
        server.createList("user", 3);
        let data = await axios.get("/api/users").then(res => res.json());
        expect(data).toEqual({
            users: [{ id: "1" }, { id: "2" }, { id: "3" }]
        });
        server.shutdown()
    });
{code}

Now, i still get get the ECONNREFUSED 127.0.0.1:80 error.... Any suggestions?

**Comment by samselikoff** [comment]
Hm - so your Vue's app request is making it to the browser?

**Comment by janeivind** [comment]
@samselikoff Decided to try with a clean slate and forked https://github.com/miragejs/vue-demo.

Installed both jest and @vue/cli-plugin-unit-mocha, as I am using the latter in my own project.
Now running with jest, the same test in my previous comment works absolutely fine :) 
Running with @vue/cli-plugin-unit-mocha throws the ECONNREFUSED error...

Code is at 
https://github.com/janeivind/vue-demo
"npm run test:jest" vs "npm run test:mocha".

**Comment by samselikoff** [comment]
Posted as a new open issue so we don't lose track of it https://github.com/miragejs/miragejs/issues/580

**Comment by XavierChevalier** [comment]
I also have the problem `ECONREFUSED 127.0.0.1:80`.

I use MirageJs on a Vue.js application with Axios. It works very well.
However, as long as I try to do unit tests, no requests are intercepted by MirageJs.

```typescript
let server: Server<AppRegistry>;
beforeEach(() => {
  server = makeServer({ environment: 'test' });
});

afterEach(() => {
  server.shutdown();
});

it('should handle Axios requests', async () => {
  const url = '/fake-url';
  server.get(url, () => new Response(200));

  const { status } = await axios.get(url);

  assert.strictEqual(status, 200);
});
```

In addition, I get the following error:
```
Error: Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.dispatchError (node_modules\jsdom\lib\jsdom\living\xhr-utils.js:54:19)
    at Request.<anonymous> (node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:675:20)
    at Request.emit (events.js:228:7)
    at Request.onRequestError (node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:223:5)
    at Socket.socketErrorListener (_http_client.js:415:9)
    at Socket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) undefined

Error: Network Error
    at createError (dist\js\webpack:\node_modules\axios\lib\core\createError.js:16:1)
    at XMLHttpRequest.handleError (dist\js\webpack:\node_modules\axios\lib\adapters\xhr.js:83:1)
    at XMLHttpRequest.<anonymous> (node_modules\jsdom\lib\jsdom\living\helpers\create-event-accessor.js:33:32)
    at innerInvokeEventListeners (node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:316:27)
    at invokeEventListeners (node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:267:3)
    at XMLHttpRequestEventTargetImpl._dispatch (node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:214:9)
    at fireAnEvent (node_modules\jsdom\lib\jsdom\living\helpers\events.js:17:36)
    at requestErrorSteps (node_modules\jsdom\lib\jsdom\living\xhr-utils.js:121:3)
    at Object.dispatchError (node_modules\jsdom\lib\jsdom\living\xhr-utils.js:51:3)
    at Request.<anonymous> (node_modules\jsdom\lib\jsdom\living\xmlhttprequest.js:675:20)
    at Request.onRequestError (node_modules\request\request.js:877:8)
    at Socket.socketErrorListener (_http_client.js:415:9)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

I tried to modify the `urlPrefix`, however the requests are not intercepted and are sent directly to the real server.
I also tried to use `axios` without interceptors, without success.

_For information, I use `Mocha` with the `@vue/cli-plugin-unit-mocha` plugin._

Do you have any suggestions?
