### ISSUE TITLE
Interference with absolute URLs

### ISSUE THREAD

**Issue by paramsinghvc** [miragejs/miragejs#313]
I have a react application in which I need to mock the business APIs but not the login api by gitlab as `https://gitlab.com/api/v4/user`. Even when I haven't explicitly stated this url in the mirage server configuration, it's being intercepted and thrown an error upon by mirage.

`Mirage: Your app tried to GET 'https://gitlab.com/api/v4/user', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?`

Do I really need to define every such route which I don't want to mock in the configuration explicitly? And even if I define it, I don't want to mock it. Rather, pass it on or relay to the actual gitlab api call.

Is there anything I'm missing?

Here's the mirage server configuration

```
import { Server } from "miragejs";

new Server({
  routes() {
    this.namespace = "";
    this.logging = true;

    this.get("/movies", () => {
      return {
        movies: [
          { id: 1, name: "Inception", year: 2010 },
          { id: 2, name: "Interstellar", year: 2014 },
          { id: 3, name: "Dunkirk", year: 2017 }
        ]
      };
    });
  }
});

```

**Comment by ryanto** [comment]
You can passthrough an entire domain using `this.passthrough('https://gitlab.com/api/**');` in your routes config.

Let us know if this solves the problem.

**Comment by paramsinghvc** [comment]
@ryanto It works.
