### ISSUE TITLE
Sapper, namespace not respected

### ISSUE THREAD

**Issue by bravo-kernel** [miragejs/miragejs#323]
Hi (again), so glad you made this framework agnostic ❤️ 

I'm trying to get mirage working with sapper to prepare a docs PR for the quickstarts guide.

Works great except one thing; it looks like mirage is catching more than the `/api` namespace. 

As you can see below mirage is intercepting a call to `/blog.json` which is unexpected. 

![image](https://user-images.githubusercontent.com/230500/74682317-0061b800-51c6-11ea-951a-e783ad125452.png)

## Additional Information

- repo containing above demo at https://github.com/alt3/sapper-mirage
- mirage loaded at https://github.com/alt3/sapper-mirage/blob/master/src/client.js 
- mirage namespace defined at https://github.com/alt3/sapper-mirage/blob/master/src/mirage.js#L18
- based on the react quickstart

Pointers appreciated ! Apologies if I'm misinterpreting expected behavior here.

**Comment by bravo-kernel** [comment]
OK, adding `this.passthrough` as shown below solves the issue. Hope this is expected behavior.

```js
   routes() {
      this.passthrough("/**");

      this.namespace = "/api"

      this.get("/users", schema => {
        return schema.users.all()
      })
    },
```

**Comment by samselikoff** [comment]
Awesome, yes nice find!

We're working on a `canHandle` API so you'll be able to do something like this:

```js
this.passthrough(request => {
  return !server.canHandle(request);
})
```

which should smooth over some of the oddities with the passthrough APIs. In fact this will likely become the default.

**Comment by bravo-kernel** [comment]
Great, I'm sure you will come up with something nice. Two more if I may:

1. would you be willing to add svelte to the quickstart guides? 
2. I see a lot of reference to `baseConfg` in the API docs, are those typos?

**Comment by samselikoff** [comment]
100% would love to get Svelte added!!

`baseConfig` should not be there, it's still supported but a holdover from e-c-mirage, we use `seeds()` now. Gonna add an issue for this + any help would be welcome!

**Comment by samselikoff** [comment]
I'm actually working on a bugfix right now so I'll go ahead and take care of this 👍

**Comment by bravo-kernel** [comment]
Awesome, I will try to come up with a PR for svelte, even though it will use sapper to demo it.

**Comment by bravo-kernel** [comment]
@samselikoff there is a lot of docs-love waiting to be merged like this one https://github.com/miragejs/site/pull/318 for svelte. Example has been verified by people who actually understand the language  :shipit:

**Comment by samselikoff** [comment]
yes! Will get to it soon or if someone else wants to give it a shot and give their +1!
