### ISSUE TITLE
Console Log Response in Angular always shows NULL

### ISSUE THREAD

**Issue by JeffBeltran** [miragejs/miragejs#329]
Expected: (example from VUE)
![image](https://user-images.githubusercontent.com/22965241/75060036-f0cac380-5492-11ea-92f2-6e17cfdfacc0.png)

Actual: (from Angular 9 new project)
![image](https://user-images.githubusercontent.com/22965241/75060196-38514f80-5493-11ea-9f35-51f835b8aefe.png)

Mirage is returning data to the app (yay) but the log isn't very helpful, not sure if this is a config issue or just the way angular works. Is it possible i'm missing a step that would cause this?

For reference, I followed [this guide](https://github.com/miragejs/site/blob/343afc39aea85df7f68a3c75e72dc677a90bbdde/src/routes/quickstarts/angular/setup.mdx) to setup Mirage.

Thanks in advance, really looking forward to getting this tool added to our workflow!

**Comment by samselikoff** [comment]
Believe someone else reported this... @romansandler did you get it solved ever?

**Comment by romansndlr** [comment]
I never got it to work either

**Comment by samselikoff** [comment]
cool thanks. We'll investigate.

**Comment by JeffBeltran** [comment]
In case this helps at all i noticed that once i setup cypress, and enabled logging the console log works within the cypress test runner. So i wonder if this has to do with how angular handles HTTP calls vs fetch (observables vs promises)

**Comment by tonivj5** [comment]
I have this problem too. I have debugged a bit and I have noticed that it's a bug on the Angular side.

Angular aborts request when the [xhr is completed](https://github.com/angular/angular/blob/master/packages/common/http/src/xhr.ts#L338) (always, either if it's success, it fails or it's unbsubscribed/aborted), for that reason the `FakeXMLHttpRequest` on abort [resets its state](https://github.com/pretenderjs/FakeXMLHttpRequest/blob/master/fake_xml_http_request.js#L309).

I'm going to create an issue in the Angular repository

**Comment by chrisjsherm** [comment]
Looks like this will be fixed in Angular 10.1.0: https://github.com/angular/angular/blob/10.1.0-next.0/packages/common/http/src/xhr.ts#L342

**Comment by tonivj5** [comment]
I think this issue can be closed :tada::tada:

It was fixed in [10.0.1](https://github.com/angular/angular/blob/master/CHANGELOG.md#1001-2020-06-26)

**Comment by samselikoff** [comment]
Awesome! Thanks for following up 👍
