### ISSUE TITLE
Fix teardown when pending requests

### ISSUE THREAD

**Issue by artemgurzhii** [miragejs/miragejs#352]
We are rewriting our `ember-cli-mirage` code to the `miragejs` so both of our ember and react apps could use the same backend during testing. And I have stuck with the problem described [here](https://github.com/miragejs/ember-cli-mirage/pull/1281) and [here](https://github.com/miragejs/ember-cli-mirage/pull/1349). I have fixed it with the code used in the PR. I don't know if there any way it could be fixed in the `miragejs` repo but at least to have some documentation about that that you can experience such problem and how to solve it would be great.

**P.S.** Thanks for the repo and awesome docs, migration took like a few hours for a few thousand lines of code.

**Comment by samselikoff** [comment]
@artemgurzhii thanks + so glad to hear the migration is going well so far!

can I see the code you ended up using that shut down your miragejs server + used `settled()`?

**Comment by artemgurzhii** [comment]
@samselikoff our migration path is not finished yet, but I can give a brief temporary sum up of how everything went. I will also describe some stuff that probably will not be interesting to you, but anyone who will search for certain keywords/problems will find that issue. I have basically moved all config from the mirage folder to the separate github repo and we are using it as the npm package. 

So I had to implicitly define all the paths, previously `ember-cli-mirage` was automatically resolving all stuff for us, but now we had to add:

```js
import { Server } from 'miragejs';
import routes from './config';
import defaultScenario from './scenarios/default';

// Models START
import ApplicationModel from './models/application';
import MultiWordModel from './models/multi-word';
// Models END

// Factories START
import ApplicationFactory from './factories/application';
import MultiWordFactory from './factories/multi-word';
// Factories END

// Serializers START
import ApplicationSerializer from './serializers/application';
import MultiWordSerializer from './serializers/multi-word';
// Serializers END

export function startMirage({
  environment = 'test'
} = {
  environment: 'test'
}) {
  console.log(`
    --------------------
    |--starting server--|
    |environment is ${environment}|
    --------------------
  `);
  return new Server({
    environment,

    models: {
      application: ApplicationModel,
      multiWord: MultiWordModel,
    },

    factories: {
      application: ApplicationFactory,
      multiWord: MultiWordFactory,
    },

    serializers: {
      application: ApplicationSerializer,
      multiWord: MultiWordSerializer,
    },

    seeds(server) {
      defaultScenario(server);
    },

    routes() {
      return routes.call(this);
    },
  });
}
```

Also, I needed to add `settled` when using test auth from the `ember-simple-auth`.

The thing I had most problems with, is to make cypress and miragejs working(ping me if you need more info). The problem was not with the miragejs but with the cypress(it doesn't want to be in friends with all other libraries). Some async/settled related cases were automatically handled by the `ember-cli-mirage` but mirage is agnostic to all frameworks and libraries and because of that, they are not handled here.

Previously we had:

```js
import {  authenticateSession } from 'ember-simple-auth/test-support';

export const authenticate = async user => {
  const sessionData = {...user}; // some user data goes here

  await authenticateSession(sessionData);
};
```

now:

```js
import {  authenticateSession } from 'ember-simple-auth/test-support';

export const authenticate = async user => {
  const sessionData = {...user}; // some user data goes here

  await authenticateSession(sessionData);

  return settled();
};
```

**Keywords**: miragejs, ember-cli-mirage, cypress, emberjs, ember-simple-auth, migration, migration path.

**P.S.** I will give more info when we finish, but here is some brief info for now.

**Comment by samselikoff** [comment]
Ok, seems like you've gotten unstuck though! I know the cypress stuff is a little gnarly, we do have a guide here with how we approached it: https://miragejs.com/quickstarts/cypress/ But I think it is not 100% complete.

Feel free to drop any more comments here if you have any questions. Going to close this for now but thanks for all the info!
