### ISSUE TITLE
How to return an image with Mirage?

### ISSUE THREAD

**Issue by JulienUsson** [miragejs/miragejs#369]
Hello,

Is it possible to intercept image request and return an image with Mirage?
I don't find anything in the doc.

Thank you.

**Comment by samselikoff** [comment]
I agree we should have something in the docs about this.

For now, what I usually do is create something like a `__test-assets` folder that gets stripped out in production, and use public URLs in my mirage mocks. Basically mirage returns the URL to an image. In production that URL would probably point to a CDN but in local dev it can point to a local file being served out of the `public` directory. Then you can make a factory that iterates through the files in that directory so you don't have to hard-code it each time.

As far as intercepting an actual image request that's not something Mirage can do, so I would stick to image URLs.

Does that make sense?

**Comment by samselikoff** [comment]
You can also of course have your imageUrls just point to unsplash or some other site that gives you back random images. But then it wouldn't work offline.

**Comment by JulienUsson** [comment]
I would like to have a code like this:

```javascript
this.get('/blueprints/:blueprintId/intensity.png', () => {
    return new Response(200, { 'Content-Type': 'image/png' }, 'data:image/png;base64....')
})
```

but after your message, i think its not possible :disappointed: 
Thank you for your help ! :smile:

**Comment by samselikoff** [comment]
No but, it's a good idea! Might be interesting to play around with a service worker one day to see if that's possible.

**Comment by SamMorrowDrums** [comment]
It does feel very achievable that we could handle responses of type Blob. When I do this, the data gets converted to `{}` which does mean that code running `URL.createObjectURL(xhr.response);` fails. I'm not sure it's specifically the remit of Mirage to mock Binary stuff, but Blob responses seem like the simplest way to do it.

```
          return new Response(
            200,
            { 'Content-Type': 'image/png' },
            new Blob([])
          );
```

For requests like:

```
xhr = new XMLHttpRequest();
xhr.open('GET', url);
xhr.responseType = 'blob';
```

**Comment by samselikoff** [comment]
@SamMorrowDrums is the idea here that the Blob is basically never serialized/deserialized?

**Comment by SamMorrowDrums** [comment]
That is what I imagined. If it's possible to simply pass the original blob to the consumer, that would offer an easy method of binary final handling. Of course most file types could be base64 decoded / encoded if we need to serialize at some step, but I think having at least one way to do this would be nice, and passing files as blob objects (where often the data doesn't even need to be valid) would help to test some APIs.

**Comment by samselikoff** [comment]
ya. Interesting. I think some people have done this in the past, maybe there's an issue in ember-cli-mirage about it. The only thing about leaking through the boundary is it might affect node support when we get there?

Maybe we need a more generalized/low-level API for a route handler, to tell Mirage not to serialize it into a string? Then you can do more interesting things like this? Would be happy to consider any such APIs.
