### ISSUE TITLE
How to selectively handle XHR requests?

### ISSUE THREAD

**Issue by kfrajtak** [miragejs/miragejs#398]
I have tried MirageJS in my E2E Cypress tests of my application. I followed the instructions and the app did not start. The reason was the server is handling all the XHR traffic and I am using `react-i18next` for localization and it is loading the locales for each language via XHR request.

```
let methods = ["get", "put", "patch", "post", "delete"];
methods.forEach(method => {
  this[method]("/api/*", async (schema, request) => {
    let [status, headers, body] = await window.handleFromCypress(request);
    return new Response(status, headers, body);
  });
});
```

And the message was
> Mirage: Your app tried to GET '/locales/cs/translation.json', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?"

The filter is `/api/*` otherwise I get `Uncaught (in promise) TypeError: Cannot read property 'content-type' of undefined`.

Then I tried this - to forward the `/api*` to Mirage and to handle the others normally (guess this is not the proper way)
```
let methods = ["get", "put", "patch", "post", "delete"];
  methods.forEach(method => {
    this[method]("*", async (schema, request) => {
      if (request.url.match(/\/api\//)) {
        let [status, headers, body] = await window.handleFromCypress(
          request
        );
        return new Response(status, headers, body);
      }
      return fetch(schema, request);
    });
  });
}
```

but that resulted in `Uncaught (in promise) RangeError: Maximum call stack size exceeded`.

**Comment by kfrajtak** [comment]
I have fixed this in the meantime - I remembered the old trick to save the old function in a variable before replacing it:
```
if (window.Cypress) {
  const oldFetch = fetch;
  new Server({
    environment: "test",
    routes() {
      let methods = ["get", "put", "patch", "post", "delete"];
      methods.forEach(method => {
        this[method]("*", async (schema, request) => {
          if (request.url.match(/\/api\//)) {
            let [status, headers, body] = await window.handleFromCypress(
              request
            );
            return new Response(status, headers, body);
          }

          return oldFetch(request.url, {
            method: request.method,
            headers: request.requestHeaders
          })
            .then(response => response.text())
            .then(body => {
              return new Response(1, [], body);
            });
        });
      });
    }
  });
}
```
The code can be improved - I am not returning the response headers and the status code is always 1.

**Comment by MartinMalinda** [comment]
I think issue could have been solved with `passthrough`.
