### ISSUE TITLE
Superagent, jest and MirageJS

### ISSUE THREAD

**Issue by rafaelchiti** [miragejs/miragejs#407]
Hey! sorry if this seems trivial but Im trying to get Miragejs with superagent and jest. The issue is that superagent when used from jest runs in 'node' mode and mirage is mocking on Fetch api (but superagent seems to be using node 'http' one). Is there any example of how to get this combo going? 

Thanks!

**Comment by ryanto** [comment]
Not trivial at all!

We've seen this happen before with HTTP clients that try to be smart about detecting their environment and using the "right" HTTP module. It get especially confusing when running SPAs with jest+jsdom in node 😵 

I just looked at the [superagent docs on browser vs node](https://visionmedia.github.io/superagent/#browser-and-node-versions) and found this

> Electron developers report if you would prefer to use the browser version of SuperAgent instead of the Node version, you can `require('superagent/superagent')`. 

Might be worth giving it a shot.

**Comment by rafaelchiti** [comment]
Thanks for getting back! that looks promising. I sadly had to switch to another project but if I take this effort back on I'll check this out. Thanks very much!

**Comment by ryanto** [comment]
Great! I'm going to close this issue but feel free to re-open if you run into anything else.
