### ISSUE TITLE
Schema response does not contain foreign keys

### ISSUE THREAD

**Issue by bravo-kernel** [miragejs/miragejs#413]
Hi there, I'm successfully using factories to create multiple records with associated records (as per the website instructions and as shown in the extract below). 

**However,** the `return schema.logEntries.all();` produced records do not contain the `logLineIds` field with the foreign keys. I am 100% they exist in the `db` because when I use the commented last-line in below example it does yield the expected result.

Am I missing something obvious here or am I expecting something that is not supported?

```js
    models: {
      logEntry: Model.extend({
        logLines: hasMany()
      }),
      logLine: Model.extend({
        logEntry: belongsTo()
      }),
    },

    factories: {
      logEntry: logEntryFactory,
      logLine: logLineFactory,
    },

    seeds(server) {
      server.createList('logEntry', 3).forEach(logEntry => {
        server.createList('logLine', 2, { logEntry })
      })
    },

    routes() {
      this.namespace = "api"; // mock all cals to `/api`
      this.timing = 1200; // simulate slow networks

      this.get("/log-entries", (schema) => {
        return schema.logEntries.all();
        //return {logEntries: server.db._collections[2]._records}
      });
  }
```

However, when I

**Comment by bravo-kernel** [comment]
OK, I expected this to be automatic but it seems a serializer is required. Adding this solves my case:

```js
    serializers: {
      logEntry: Serializer.extend({
        include: ['logLines']
      })
    },
```

https://miragejs.com/api/classes/serializer/

**Comment by samselikoff** [comment]
Yes. Glad you posted though because this is a confusing point in mirage.

You can also use the [serializeIds](https://miragejs.com/api/classes/serializer/#serialize-ids) property if you just want the ids to be included with the parent resource.

**Comment by benjamindavid** [comment]
I'm trying to get ids of relationships included in the response but the `serializeIds` property doesn't seem to have any effect:

```
serializers: {
    application: JSONAPISerializer.extend({
        serializeIds: 'always'
    }),
},
```

Is the `serializeIds` supposed to work with the `JSONAPISerializer` as well?

**Comment by samselikoff** [comment]
@benjamindavid I don't think so bc it's not part of the spec, I think..

Can you share the HTTP response you're trying to mock?

**Comment by richardmarbach** [comment]
I'm having a similar issue to @benjamindavid. The response I'm trying to mock:
`
[
  {
      id: 1,
      username: 'user1',
      comments: [{
            id: 2,
            text: 'my comment',
            user_id: 1
      }]
  }
]
`

I've setup the serializer to always include id's and embed the includes, but the `user_id` isn't included:
`
Serializer.extend({
    serializeIds: 'always',
    root: false,
    embed: true,
})
`

Is there a way to customize the serializer to include the foreign id in the embedded resource?

**Comment by richardmarbach** [comment]
If I'm understanding the behavior correctly, this is currently impossible?

https://github.com/miragejs/miragejs/blob/master/lib/serializer.js#L705
