### ISSUE TITLE
Logging in console always show null when user angular httpCliend

### ISSUE THREAD

**Issue by Jesniphat** [miragejs/miragejs#415]
I user HttpClient of angular9 to call mock mirage js but in console tab it always show null but actually I got response. this is my code.

**Angular code**
```
this.http.get('api/business-type').subscribe((res) => {
      console.log(res);
  });
```

**Mirage js code**
```
import * as businessType from './mockFile/BusnessType.json';

export function mockServer() {
  return new Server({
    routes() {
      this.passthrough();
      this.namespace = "api";
      this.get('/business-type', () => businessType.default); // JSON Object
    },
  })
};
```
**console**
![image](https://user-images.githubusercontent.com/16810190/79321404-846dbd00-7f35-11ea-8499-7e8ec800fda1.png)

**Comment by zoltan-nz** [comment]
@Jesniphat You can see a Mirage.js with Angular 9 implementation here: https://github.com/zoltan-nz/hello-angular/tree/master/mirage

Hope it gives you a few ideas.

**Comment by Jesniphat** [comment]
> @Jesniphat You can see a Mirage.js with Angular 9 implementation here: https://github.com/zoltan-nz/hello-angular/tree/master/mirage
> 
> Hope it gives you a few ideas.

I tried but response still null
![image](https://user-images.githubusercontent.com/16810190/79437465-6b7c0f00-7ffc-11ea-8da4-0edc6b9e0f42.png)

**Comment by zoltan-nz** [comment]
Let's play a little bit with it here: https://codesandbox.io/s/miragejs-angular-sandbox-3ebtu?file=/src/main.ts:319-332 ;)

**Comment by zoltan-nz** [comment]
Work as expected. 
![image](https://user-images.githubusercontent.com/1009783/79449490-69837180-8037-11ea-980a-f648e6891bab.png)

https://codesandbox.io/s/miragejs-angular-sandbox-3ebtu?file=/src/main.ts

**Comment by zoltan-nz** [comment]
> import * as businessType from './mockFile/BusnessType.json';

I suppose this typo isn't in your code base only here... ;)

**Comment by Jesniphat** [comment]
> > import * as businessType from './mockFile/BusnessType.json';
> 
> @Jesniphat I suppose this typo isn't in your code base only here... ;) `BusnessType.json`

I don't think so.
I think because of httpclient when I use fetch it show logging correct.

https://stackblitz.com/edit/angular-67bn2f?file=src%2Fapp%2Fapp.component.ts

![image](https://user-images.githubusercontent.com/16810190/79456301-7349ac80-8018-11ea-97b2-df2df7070475.png)

**Comment by zoltan-nz** [comment]
@Jesniphat Have you found the solution, because it works for me as expected.
![image](https://user-images.githubusercontent.com/1009783/79672143-8e3c3c80-8223-11ea-9787-f8198aff6480.png)

**Comment by Jesniphat** [comment]
> @Jesniphat Have you found the solution, because it works for me as expected.
> ![image](https://user-images.githubusercontent.com/1009783/79672143-8e3c3c80-8223-11ea-9787-f8198aff6480.png)

I don't found the solution yet. The real response is already there but in logging of miragejs it still null when I use angular httpclient but when use fatch it have miragejs logging response correctly.
In your screen capture if you click to expand at "Mirage: [200] GET api/all-country" under "Line 20" you will see "Response" null.

**Comment by zoltan-nz** [comment]
@Jesniphat ah, I see... it is not really related to TypeScript or Angular, it could a standard behaviour or maybe a bug.

![image](https://user-images.githubusercontent.com/1009783/79720104-04c85f80-8334-11ea-8775-d1482e7d194a.png)

@samselikoff Hi Sam, the `requestBody` is null here however, the server already responded the expected value. Is this a bug or intentional?

![Screen Shot 2020-04-20 at 6 24 31 PM](https://user-images.githubusercontent.com/1009783/79720252-4c4eeb80-8334-11ea-8337-a6af1d36d0b4.png)

**Comment by ryanto** [comment]
This looks like a bug, but when I try to download the angular app from stackblitz it won't compile.

I'd love to be able to get this running outside of stackblitz so I can dig into what's happening with http client and mirage. Any chance you could share a github repo?

**Comment by ryanto** [comment]
Oh, looks like we already have an issue for this one: https://github.com/miragejs/miragejs/issues/329

I'm going to close this issue and use #329 as the tracking issue.
