### ISSUE TITLE
How does mirage compare to msw (mock service worker)?

### ISSUE THREAD

**Issue by HeyItsJs** [miragejs/miragejs#418]

**Comment by ryanto** [comment]
Great question! I'm going to close this issue since there's some discussion about mirage and msw happening here: https://github.com/miragejs/miragejs/issues/449

**Comment by samselikoff** [comment]
You can now find this on the site! https://miragejs.com/docs/comparison-with-other-tools/#msw

**Comment by HeyItsJs** [comment]
Must say that it is very nicely written! Impressed by the overall docs standard maintained😀

**Comment by samselikoff** [comment]
Thank you very much!

I hope one day soon we can shrink the "Disadvantages" section by getting the devtools working in Mirage 😄

**Comment by MrLoh** [comment]
@samselikoff have you considered just replacing pretender with msw for the underlying implementation? Is there something that really blocks that approach. I want to use mirage on a node GraphQL gateway.

**Comment by samselikoff** [comment]
Yeah we’ve talked about it! Think it would be worth someone exploring what that would involve. Pretender has caused us a bit of headaches over mirage’s life so I’m a bit nervous about taking on another dependency we don’t fully control but I’m definitely open to it.

**Comment by NullVoxPopuli** [comment]
If anyone wants to spike out the replacement of pretender for MSW, I have a sample project here (ember-data-resources) that shows how easy / little code it is to provide everything pretender does (and more!), while also giving you network-tab level debugging, and not polluting your logs:
https://github.com/NullVoxPopuli/ember-data-resources/blob/main/tests/unit/-mock-data.ts

You still get per-test (or per-module) customization, too
