### ISSUE TITLE
Help with running a debugger

### ISSUE THREAD

**Issue by cah-briangantzler** [miragejs/miragejs#428]
I am working on a PR and could use some help debugging the code.   I have use node --inspect a little, and assume that should work here, but cant quite figure out the command line to debug the running tests and to get a debugger statement in the code to work.

Also, any way to run just one test to shorten my cycle. Not familiar with jest and did read the docs. test.only didnt seem to work for me.

Thanks

**Comment by samselikoff** [comment]
Believe this should work regarding running one test https://stackoverflow.com/a/44446669/1406664

Debugger is a little more complicated in jest, think you need --inspect-brk... I would look up a node debugging tutorial/vscode debugging tutorial as I think that's the easiest way to get it going

**Comment by cah-briangantzler** [comment]
I had used --inspect-brk but couldnt find the files loaded so I could put a break point.    

Read up on the jest again and looks like `-t "patterm"` works like embers --filter

And why I didnt se this before but I use intellij and its got a green arrow to the left. It lets me run a specific test and also respects debugger statements. If I had only seen that before i wouldnt have bothered you.

Thanks
