### ISSUE TITLE
Can't import RestSerializer (or any other serializer)

### ISSUE THREAD

**Issue by juanghurtado** [miragejs/miragejs#433]
I'm trying to use `RestSerializer`, but I can't import it. The error message I keep getting is:

```
Module '"miragejs"' has no exported member 'RestSerializer'
```

I'm using `"miragejs": "^0.1.37"` in an Angular 8 project, using Typescript. I have no idea about what could be happening. Any ideas?

Thanks a lot!

**Comment by dushr** [comment]
I have the same issue, I am using typescript with a Vue3 project.

**Comment by zoltan-nz** [comment]
Hi @juanghurtado and @dushr.

Thanks for your messages. Yep, Serializer support is already added https://github.com/miragejs/miragejs/pull/397

I guess @samselikoff will cut a new release soon so Serializers will be supported in TypeScript environment as well. ;)

**Comment by samselikoff** [comment]
My bad guys 🙈

Just cut a release, 0.1.38 is up! https://github.com/miragejs/miragejs/releases/tag/v0.1.38

**Comment by samselikoff** [comment]
Closing for now – let me know if you run into any problems.

**Comment by juanghurtado** [comment]
Thanks a lot!
