### ISSUE TITLE
TypeScript complains about the model type does not exist on the schema

### ISSUE THREAD

**Issue by modularcoder** [miragejs/miragejs#460]
Hi!
First of all, thanks for the great project!

I'm running into an issue when I'm trying to call the schema methods in the route handlers in TypeScript environment. TS saying:

`Property 'users' does not exist on type 'Schema<Registry<Record<string, ModelDefinition<{}>>, Record<string, FactoryDefinition<{}>>>>'`

![image](https://user-images.githubusercontent.com/3959008/81367241-b8379f00-90fd-11ea-951e-f2e48bc9960c.png)

Here's the CodeSandbox URL:
https://codesandbox.io/s/nifty-dew-3g0kj?file=/src/index.tsx

Of cause I could have defined the schema in the handler function as "any", but that seems kind of "meh" solution. So I was wondering if there's a good way of using that, or I'm missing anything?

Thanks!

**Comment by asantos00** [comment]
Hi @modularcoder,

I guess you can emulate the same behaviour by doing `schema.all('user')`.

To enable better autocomplete you can also define a type for the schema and use it to set the type of the parameter like the following:

```js
 
type AppRegistry = Registry<{ user: typeof UserModel }, { /* factories can be defined here */ }>
type AppSchema = Schema<AppRegistry>

// And then on the route handler use like the following:
this.get('/users', (schema: AppSchema) => {
  return schema.all('wine');
})
```

And by doing this you even have autocomplete for the strings to use inside the `all` method.

I guess it should/can be automatically inferred by passing the `AppRegistry` like `new Server<AppRegistry>` but I couldn't get it working.

Hope it solved your problem

**Comment by modularcoder** [comment]
@asantos00 thanks a lot for your response!

**Comment by rikutiira** [comment]
I'm also having issues with typing the models so that schema doesn't complain (eg. trying to do `schema.create('user, data)`) but I can't get the types working because miragejs doesn't export `Schema` type. Was this changed or is there some way I can access it @modularcoder ?

**Comment by haluvibe** [comment]
me too, in your example how would you type UserModel then?

**Comment by haluvibe** [comment]
Would be great if you could show the solution in codesandbox

**Comment by haluvibe** [comment]
@asantos00

**Comment by bjolletz** [comment]
I also didn't quite understand the use of `UserModel`. Some actual code would have been great as it would be fantastic to get this working.

**Comment by sohara** [comment]
For people wanting a more complete example of how @asantos00's solution could work, I came up with this based on the example and Mirage's type definitions.

```typescript
import {
  createServer,
  Factory,
  Model,
  Response,
  Registry,
  RestSerializer,
  Server,
} from 'miragejs';
import { ModelDefinition } from 'miragejs/-types';
import Schema from 'miragejs/orm/schema';


type Buyer = {
  name: string;
}

const BuyerModel: ModelDefinition<Buyer> = Model.extend({});

type AppRegistry = Registry<
  {
    buyer: typeof BuyerModel;
  },
  {}
>;
type AppSchema = Schema<AppRegistry>;
```

Then in your route handlers, for example you can get typed variables when calling e.g. `find`, `create`, etc on the schema:

```typescript
const buyer = schema.find('buyer', buyerID);

/* buyer.name is a known typed string property on buyer, with completion in IDE (vscode), etc. */
console.log(buyer.name);
```

**Comment by psbanka** [comment]
fwiw, here is a complete example that passes typing

https://codesandbox.io/s/condescending-davinci-kzthyn?file=/src/index.tsx

**Comment by nerdo** [comment]
Thanks @sohara !

It would be great if an example like this was made available in the MirageJS documentation.

**Comment by josefarrugia** [comment]
Thanks @sohara that was really helpful! I had to slightly edit the code as `Registry` and `Schema` are types and should be imported as follows respectively: 

````js
import type { Registry } from 'miragejs';
import type Schema from 'miragejs/orm/schema';
````
