### ISSUE TITLE
Passthrough for assets works only first time on page load

### ISSUE THREAD

**Issue by m0t0r** [miragejs/miragejs#486]
Hello,

I setup `passthrough` for assets like this:

```ts
export function startMockServer({ environment = 'test' }) {
  return new Server({
    environment,
    urlPrefix: 'http://localhost:3000',
    namespace: 'api',
    routes() {
      this.passthrough('http://localhost:4200/assets/**');

      this.get('config', () => {
        return { content: {} };
      });
    },
  });
}
```
when I open `http://localhost:4200` for the first time, I see all assets are loaded and Mirage reports passthrough for them as expected but if I refresh the page, Mirage shows errors that it 
can't load any of the assets: 

```
Error retrieving icon: Mirage: Your app tried to GET 'assets/icons/menu.svg', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?
```
I tried to move `passthrough` below mock endpoints, also moving `urlPrefix` and `namespace` inside `routes` and configuring them after `passthrough` route but got same result.

Am I configuring Mirage in a wrong way or there is an issue ?

Thanks

**Comment by samselikoff** [comment]
Hm interesting. I usually don't need to configure Mirage to ignore asset requests.

What's the current domain for your local site, is it port 3000 or port 4200?

The fact that the behavior changes after you reset the page is also bizarre. How are you calling `startMockServer()`?

**Comment by m0t0r** [comment]
I forgot to mention that is an Angular project. Frontend is running on port 4200, but the API is on port 3000.  I am calling `startMockServer ` in `main.ts` (which exists in every angular project) like this:

```ts
if (environment.mockApi) {
  startMockServer({ environment: 'development' });
}
```

**Comment by samselikoff** [comment]
Hm what about trying two passthroughs, one for each port? (Though in theory you should only need one for the asset server...)

If you create a project that reproduces the issue I’d be happy to take a look!

**Comment by m0t0r** [comment]
@samselikoff thanks for you reply. Unfortunately, I can't reproduce this issue when I setup a small project, even though, I did all steps that are in my actual project and everything works as expected every time. My actual project is private, unfortunately I can't share it. Do you have some tips/ideas what could possibly change behavior of Mirage ? Yes, I use latest `0.1.40` version. Thanks

**Comment by m0t0r** [comment]
After quite a bit of debugging I still wasn't able to figure out why that issue happens in my project but fortunately I found out that you can pass a function to `passthrough` and  solved it for me and now it works as expected every time:
```ts
this.passthrough(request => request.url.includes('assets'));
```
