### ISSUE TITLE
Documentation example incorrect

### ISSUE THREAD

**Issue by jd0e** [miragejs/miragejs#530]
I believe that there is a bug in the example over here:
https://miragejs.com/docs/main-concepts/factories/#the-association-helper

First example states:
```
import { Server, Factory } from "miragejs"

new Server({
  factories: {
    user: Factory.extend({
      afterCreate(post, server) {
        if (!post.user) {
          post.update({
            user: server("user"),
          })
        }
      },
    }),
  },
})
```

I believe `afterCreate()` receives two arguments:
- the model it is being called from 
- server

In the example above `afterCreate()` received `post` instead of `user`, while being called from within `user` model.

I think the above example should be about `post` model.

**Comment by samselikoff** [comment]
Woof that was super confusing 🙈 Thank you for opening this!
