### ISSUE TITLE
Add note to association helper documentation about not supporting polymorphic relationship.

### ISSUE THREAD

**Issue by jd0e** [miragejs/miragejs#531]
Hi, 

why I am still trying to figure out how to seed polymorphic models (https://stackoverflow.com/questions/62556674/how-to-seed-models-with-polymorphic-one-to-one-relationship-in-mirage-js) I stumbled across this error:

`Mirage: You're using the association() helper on your comment factory for blogPost, which is a polymorphic relationship. This is not currently supported."`

It would be nice to update docs saying that it is currently not supported.

**Comment by samselikoff** [comment]
Note added here https://github.com/miragejs/site/commit/fa1bdd9ee3c67b22b68af30a6b8245d587f8d6b4

Sorry again you're running into all these issues! I answered your SO question but here's the REPL link just in case:

http://miragejs.com/repl/v1/144

**Comment by jd0e** [comment]
Thanks!
