### ISSUE TITLE
Is it possible to seed polymorphic one to one relationship models?

### ISSUE THREAD

**Issue by jd0e** [miragejs/miragejs#534]
Hi,

I can't find a way to seed one to one, polymorphic relationship models. I either end up with :
- no "...ableId" relationship,
- with extra model,
- maximum call stack size exceeded.

Here is my thought process for models:

```     
      blogPost: Model.extend({
        comment: belongsTo(),
      }),

      picture: Model.extend({
        comment: belongsTo(),
      }),

      comment: Model.extend({
        commentable: belongsTo({ polymorphic: true }),
      }),
```

and here is the factory:
```
      blogPost: Factory.extend({
        title: "Whatever",
        afterCreate(blogPost, server) {
          let comment = server.schema.comments.create();
          comment.createCommentable("blogPost", blogPost);
          blogPost.update({
            comment,
          });
        },
      })
```

above ends in error: Maximum call stack size exceeded, which makes sense.

So, modifying the factory to:

```
      blogPost: Factory.extend({
        title: "Whatever",
        afterCreate(blogPost, server) {
          let comment = server.create("comment");
          comment.commentableId = { id: blogPost.id, type: "blogPost" };
          blogPost.update({
            comment,
          });
        }
      })
```

above ends in commentableId being null:

![image](https://user-images.githubusercontent.com/67147779/86009078-a72a5080-ba11-11ea-925f-4c99580a6347.png)

So trying to follow the docs and use `createCommentable()`:

```
      blogPost: Factory.extend({
        title: "Whatever",
        afterCreate(blogPost, server) {
          let comment = server.schema.comments.create();
          comment.createCommentable("blogPost");
          comment.commentableId = { id: 1, type: "blogPost" };
          blogPost.update({
            comment,
          });
        },
       })
```

and that leads to extra blogPost being created with no association, but the second has got correct association:

![image](https://user-images.githubusercontent.com/67147779/86009637-5b2bdb80-ba12-11ea-968c-d3c1f198a67a.png)

Adding traits to the mix makes it even more awkward... 

Is there a way to actually seed polymorphic, one to one related models using factory and `afterCreate()` ? 

Thanks

**Comment by samselikoff** [comment]
Finally catching up on issues and answered your SO question [here](https://stackoverflow.com/a/62734871/1406664).

For reference here is the REPL: http://miragejs.com/repl/v1/144

Does it make sense?

**Comment by jd0e** [comment]
It does. Thanks
