### ISSUE TITLE
New Domain Coming Available

### ISSUE THREAD

**Issue by ericdmoore** [miragejs/miragejs#560]
Around a year ago, I too started looking at domains for a project. I looked for miragejs.com - and had to move on miragejs.org - anyway i am moving on from this name. And love your execution on you project. 

So anyway I am not renewing. And miragejs.org will be available soon. Just FYI. Keep up the good work.

**Comment by samselikoff** [comment]
Oh awesome! Thank you very much for letting me know Eric, really appreciate that!

Will think on it and maybe circle back and pick it up 👍

**Comment by ericdmoore** [comment]
For sure, and if not, no big deal - it will just go back to publicly available.
