### ISSUE TITLE
urlPrefix and passthrough() are not working together

### ISSUE THREAD

**Issue by Kalpesh300** [miragejs/miragejs#584]
Issue type: **Bug**

**Current Behavior:**
I have set up my server as below:

```
  const server = new Server({

    routes() {
      this.urlPrefix = 'api';

      this.get('users', () => {
        return [];
      });

      this.get('meta-data', () => {
        return {};
      });

      this.passthrough();
    }

  });
```
The issue is I have another library for internationalization which makes a request for a static JSON file that contains the translation data. 
If I set a `urlPrefix` or `namespace` property of the server, it throws the error as miragejs tries to intercept that request. 

**Expected Behavior:** 
If I add the method `this.passthrough()` in the `routes()` it should not throw an error and miragejs should allow that request to pass through.

**Comment by samselikoff** [comment]
Sorry you're running into this! What is the full request you're trying to make that Mirage is intercepting?

**Comment by Kalpesh300** [comment]
I have a static JSON file on the server. I am accessing that JSON file with HTTP GET request.

**Comment by samselikoff** [comment]
This is a sort of confusing part of the routes API but if you specify `urlPrefix` or `namespace` it applies to every route definition that follows it, and also affects calls to `this.passthrough()`.

All you need to do is reset it before calling `passthrough()` and all current origin requests should start passing through:

https://miragejs.com/repl/v1/311

**Comment by samselikoff** [comment]
Let me know if you are still running into any problems!
