### ISSUE TITLE
afterCreate can't call this._super(...arguments) by factory model

### ISSUE THREAD

**Issue by mohsalim** [miragejs/miragejs#585]
It seems you can't call super to get the parent class `afterCreate` definition. `this` doesn't exist because it seems we extract `afterCreate` and call it as a static function. The best work around is to export a `afterCreateHelper` and call that, but that seems like an unusual workaround. 

`factories/base-camera.js`:
```javascript
import BaseDeviceFactory from './base-device';

export default BaseDeviceFactory.extend({
    someProperty: true,

    afterCreate(camera, server) {
        camera.update('snapshot', server.create('vid-snapshot', {
            id: camera.id
        }));
    }
});
```

`factories/camera.js`:
```javascript
import BaseCamera from './base-camera';

export default BaseCamera.extend({
    afterCreate(camera, server) {
        this._super(...arguments); // This will fail!

        camera.update('videoSource', server.create('live-video-source', {
            id: camera.id
        }));
    }
});
```

**Comment by samselikoff** [comment]
Sadly Mirage's class system is a bit legacy and super doesn't really work correctly here. I think I would just export a helper function and use it in both factories if you want two modules to share behavior.

We do have plans to rework the class system but currently are focused on fixing bugs and shipping a 1.0. Sorry about the inconvenience!

Closing for now but please let me know if you have any more questions.
