### ISSUE TITLE
Mock Websockets

### ISSUE THREAD

**Issue by MartinMuzatko** [miragejs/miragejs#588]
Hi! Websockets are important for us for live updates of the content.
They are hard to test, hard to debug and hard to set up. The tooling around Websockets is significantly less advanced than HTTP and often proprietary unfortunately.
Then they have to be server controlled and the server needs to push and react on client messages.
Are there any plans or possibilities to make websockets less painful?
The biggest problem I see here, is that people would have to write adapters for their dialects.

Would like to read your suggestions or ideas! 

Cheers

**Comment by samselikoff** [comment]
This is absolutely possible and I've done it before using [mock-socket](https://github.com/thoov/mock-socket).

I don't have an example handy but see this issue for some more discussion: https://github.com/miragejs/discuss/issues/23

Currently have no immediate plans for this but if someone was motivated and wanted to pick up the work on a first-class API I'd be happy to help!

**Comment by samselikoff** [comment]
If you try to get something like mock-socket wired up and have trouble, I'd also be happy to take a look at a project and point you in the right direction.
