### ISSUE TITLE
Mirage does not play well with firebase

### ISSUE THREAD

**Issue by alistairholt** [miragejs/miragejs#600]
I'm using the npm `firebase` package alongside mirage in a React app. When I make a Firebase auth request, Mirage intercepts the HTTP request and `firebase` returns an `auth/network-request-failed` error. I have `this.passthrough()` at the bottom of my routes config in `createServer` but it still doesn't work. Any ideas?

**Comment by samselikoff** [comment]
Hm. Do you have `namespace` or `urlPrefix` set?

**Comment by JeffBeltran** [comment]
I was just looking how to fix this same issue @alistairholt . 

Taking a look at the docs at the bottom of the overview section for pass through 

```
    // If your API requests go to an external domain, pass those through by
    // specifying the fully qualified domain name
    this.passthrough("http://api.acme.com/**");
```

Just like you, having `this.passthrough()` did not solve the issue, but once i added the FQDN it worked without a hitch `
this.passthrough('https://www.googleapis.com/identitytoolkit/**');`

Now i can ignore mocking the auth flow... for now

@samselikoff is there a "recipe" section for some common things like this? Like a simple gist or write up for mocking out 3rd party tools like firebase? if not, once i get around to doing it for this new project im working on maybe i'll open a PR for the docs?

**Comment by samselikoff** [comment]
I think the best place would be the new https://github.com/miragejs/examples repo. If you get a working example with Firebase, that would be a fantastic addition!

**Comment by sbatson5** [comment]
FYI, I ran into the same problem but doing just `identitytoolkit` didn't work for me. I was doing OAuth with google through firebase and had to add all of these:

```
this.passthrough('https://www.googleapis.com/**');
this.passthrough('https://securetoken.googleapis.com/**');
this.passthrough('https://play.google.com/**');
this.passthrough('https://accounts.google.com/**');
```

**Comment by timrbula** [comment]
For anyone looking at this in 2021, I was able to get it to work locally with 
`this.passthrough("https://identitytoolkit.googleapis.com/**");`

Looks like the auth domain has changed.

**Comment by alistairholt** [comment]
Closing the issue. Thanks, everyone!

**Comment by martianshaan** [comment]
Thanks @timrbula  for help ! Thanks @alistairholt  for creating this issue .
