### ISSUE TITLE
Mirrage throws an undefined error even with passthrough enabled.

### ISSUE THREAD

**Issue by quentincaffeino** [miragejs/miragejs#603]
The code:

```js
import { Server } from "miragejs"

new Server({
  routes() {
    this.passthrough()
  }
})
```

The fetching code:

```js
return fetch(endpoint + directory + `/${providerName}.json`)
```

Error message: Mirage: Your app tried to GET 'http://localhost:8503/providers/...', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?

I wanted to mock `/api` namespace so I tried adding it, no luck, it still throws even tho it has passthrough enabled.

Also I have a question, would mirage have any problems with running multiple instances simultaneously? I'm developing a microfrontend project, all microfronteds run on the same page (not iframe based).

**Comment by ohcibi** [comment]
> Also I have a question, would mirage have any problems with running multiple instances simultaneously? I'm developing a microfrontend project, all microfronteds run on the same page (not iframe based).

Currently that's not possible, you can however integrate all fake endpoints into one instance. If you need to change the actual behavior of the requested endpoints, you have to choose different code paths within your endpoint handler manually .

**Comment by quentincaffeino** [comment]
Thanks. Anyway I considered to stop using mirage within this project because I couldn't set it up. This was probably some problem with microfrontend setup. So I guess issue is resolved.

**Comment by samselikoff** [comment]
@quentincaffeino Sorry you ran into issues - the passthrough API is confusing atm and we have plans to change it.

Was `localhost:8503` the same domain that your app was actually running on? If not you might have needed to specify a fully qualified domain name in passthrough:

```js
// if your dev server is localhost:3000 but API requests are to localhost:8503, you can pass them through like this:
this.passthrough('http://localhost:8503/**');
```

**Comment by quentincaffeino** [comment]
@samselikoff nice to hear that.

Yeah, I was requesting different address. Sadly can't test this as I'm no longer using mirage in that project. I found that it is easier to setup simple json server for development.

But I really like mirage in my other projects! Thanks for awesome work)

**Comment by samselikoff** [comment]
No problem + appreciate you posting. Passthrough + integration is the #1 issue people run into and I think it will make sense to add proper server option (either via node or service worker) to Mirage soon. We are hoping to do it soon after closing existing bugs and shipping a v1.

Sorry again you ran into this!
