### ISSUE TITLE
Using in conjunction with react-refetch?

### ISSUE THREAD

**Issue by StudioSpindle** [miragejs/miragejs#622]
We're using [react-refetch](https://github.com/heroku/react-refetch) in our project. Does anyone have any expericence with  using miragejs in conjunction with react-refetch. 

It's passing through `Mirage: Passthrough request for GET [object Request]`.

**Comment by samselikoff** [comment]
That usually means `this.passthrough()` is in your `routes()` hook somewhere. Do you want it to pass through or are you trying to have Mirage intercept it?

**Comment by StudioSpindle** [comment]
Doh! That is probably it then. My use-case was that I wanted to log what requests were done to see if I was missing some. 

But I misunderstood the API and didn't see that this.passthrough needed to be outside the routes. Thank you very much!
