### ISSUE TITLE
Cannot combine handling and passthrough for the same resource

### ISSUE THREAD

**Issue by alina-beck** [miragejs/miragejs#623]
What I need to achieve is to only handle a few of my endpoints with MirageJS (to get certain responses in my e2e tests) and have all other requests pass through to my actual API.

The empty `passthrough()` function, as suggested in the docs, didn't work for me at all, but using a function that compares the `request.url` and `request.method` with the routes I am handling in MirageJS and returning `true` for all other requests does the trick. So far, so good.

The issue now is that I need to catch `PUT` requests to `https://api.myapp.com/user` in MirageJS, but let `GET` requests to that same url pass through. This gives me the error `this.put() is not a function` when the `PUT` request is sent (not during setup). The `GET` request, which is sent first, is being passed through as it should. I tried to solve this in several ways, including `this.resource('user', { only: ['update'] })` but to no avail.

The only way I got this working is by also handling the `GET` request with MirageJS – which is not what I want because it means I'd have to copy the exact response from my actual API.

Here is my latest, not working setup:
```
    window.server = new Server({
        routes() {
            this.urlPrefix = 'https://api.myapp.com';
            this.resource('user');
            this.put('/user', () => console.log('put user with mirage'));
            this.passthrough(request => {
                if (request.url === 'https://api.myapp.com/user' && request.method === 'PUT') {
                    return false;
                }
                return true;
            });
        },
    });
```

**Comment by samselikoff** [comment]
Sorry you're running into this! I know the current passthrough API is annoying and confusing.

The call to `passthrough()` is actually affected by `urlPrefix` and `namespace` values that were set prior to calling it. Could you try this and see if it works?

```js
window.server = new Server({
  routes() {
    this.urlPrefix = 'https://api.myapp.com';
    this.resource('user');
    this.put('/user', () => console.log('put user with mirage'));

    // Reset urlPrefix before calling passthrough
    this.urlPrefix = '';
    this.passthrough();
  },
});
```

**Comment by alina-beck** [comment]
Sorry for the late reply! Your suggestion doesn't work for me, I get several errors like this one (also for routes not using the same `urlPrefix`):
```
[Error: Mirage: Your app tried to GET 'https://api.myapp.com/settings', but there was no route defined to handle this request.
Define a route for this endpoint in your routes() config. Did you forget to define a namespace?]
```

Which is why I was so explicit in my `passthrough()` function in the first place. But I can live with that! The only big issue is not being able to mock the `PUT` method and passthrough the `GET` method for the same route.

**Comment by samselikoff** [comment]
I think I might not be understanding exactly what you're trying to do. Here's a REPL that handles PUT but lets GET (and other verbs) pass through:

https://miragejs.com/repl/v1/452

Is that what you're trying to accomplish?

**Comment by alina-beck** [comment]
This is exactly what I'm trying to do – but can't get to work. If this is working in your example, though, I'm sure it has to do with the fact that my `passthrough()` function is not working as it should...

By default, my Mirage server is trying to handle _all_ requests and the empty `passthrough()` function does nothing for me. For most requests it's fine to define a wildcard (like `passthrough(https://codepush.appcenter.ms/**)`) but of course that doesn't work for requests to endpoints I actually want to handle.

As a workaround I am now mocking all methods (in this case `GET` and `PUT`) for a specific route.

One issue could be that I am using Mirage in e2e tests for a React Native app and the setup is a bit weird there – I'm using [detox](https://github.com/wix/Detox) as a test framework, which needs to build and bundle the app (including the Mirage server) before running any tests. I tried setting up Mirage in the test files themselves but then it ended up on a different `window` instance and didn't catch any requests. Not sure if and how this is related, since my current setup is working fine, except for this `passthrough` issue, but thought it might be worth mentioning. :shrug:

**Comment by samselikoff** [comment]
Could you upload a simplified reproduction so I could take a closer look? Really helps in situations like this!

**Comment by alina-beck** [comment]
Really sorry, but I don't have time for that and am not allowed to share the repo I am working on... Wish I could be more helpful! 😕

I'll just stick with my workaround for now – feel free to close this issue if you want.

**Comment by samselikoff** [comment]
Ok sorry about that - closing for now but feel free to drop more comments if you run into anything! And keep an eye out for new passthrough API hopefully coming soon.
