### ISSUE TITLE
passthrough() passes through "/" even though it has a handler when query params are included.

### ISSUE THREAD

**Issue by GV94** [miragejs/miragejs#638]
The project I am working on fetches site data for the current route by appending `?asjson=true`.

When I make a request for `localhost:3000/?asjson=true`, it passes the request through, even though it has a handler for `"/"`.

My server setup

```
export function makeServer({ environment = "development" } = {}): MockServer {
    const server = new Server<MockServerInterface>({
        environment,
        namespace: "",
        timing: 0,
        models: {
          someModel: Model
        },

        seeds(server: Server<MockServerInterface>) {
            seeder(server);
        },

        routes() {
            /**
             * Pages
             */
            this.namespace = "";

           
            // Start page, 
            this.get("", () => startPage);
            // this.get("/", () => startPage);
            // this.get("/?asjson=true", () => startPage);

            /**
             * API
             */
            this.namespace = "api";

            this.get('/someApiRoute', () => something)

            this.namespace = "";

            //  Pass through the rest
            this.passthrough();
        },
    });

    return server;
}
```

If I remove this.passthrough(), it correctly intercepts the request.

**Comment by samselikoff** [comment]
Yep, unfortunately query params aren't treated as separate routes. So in this case I think you need to use the function version of passthrough:

```js
this.passthrough(request => {
  return !request.queryParams.asjson;
});
```

**Comment by GV94** [comment]
I believe this solves my problem. However, I can't access `request.queryParams`, despite I see the property being present if I inspect the request object. The problem seems related to #359 and the final comments of #281 .

**Comment by GV94** [comment]
I used this approach to get around the problem of not being able to access `request.queryParams` for now. 

```
this.pretender.unhandledRequest = (verb, path, request) => {
this.pretender.passthroughRequest(verb, path, request);
};
```

**Comment by samselikoff** [comment]
Ugh bummer! I verified and reopened #359.

**Comment by GV94** [comment]
Thank you for your assistance!

**Comment by samselikoff** [comment]
Closing this for now since 359 is tracking.
