### ISSUE TITLE
Issue with numeric ID's

### ISSUE THREAD

**Issue by thec0keman** [miragejs/miragejs#648]
With a custom identity manager:
```
    identityManagers: {
      application: class extends IdentityManager {
        fetch() {
          const id = this.get();
          this._ids[id] = true;
          this.inc();
          return id;
        }
      },
    },
```

ID's are correctly generated as numbers, however there is an issue with looking up records.  If you add a `user`, and confirm that it is in `schema.db.users` with an ID, `schema.users.find` with that ID will return no data.

Other than the ORM piece being broken, this also will break factories that use the `association` helper, because they cannot validate that the association was properly set up.

**Comment by samselikoff** [comment]
Hm. Might be some background here but agree this is confusing. Open to fixes.

https://github.com/miragejs/ember-cli-mirage/issues/67
https://github.com/miragejs/ember-cli-mirage/issues/891

**Comment by samselikoff** [comment]
Can't remember all the history but might be best to leave ids as strings in the db and use serializer to turn them into ints.
