### ISSUE TITLE
Runtime error on Next.js with mirage

### ISSUE THREAD

**Issue by djKooks** [miragejs/miragejs#651]
Hello,
I'm trying to setup miragejs with my Next.js Project.
But when I setup mirage server with `<Link>` in Next.js it shows following error.

```
import { Server } from "miragejs"

new Server({
  routes() {
    this.get("/api/movies", () => ({
      movies: [
        { id: 1, name: "Inception", year: 2010 },
        { id: 2, name: "Interstellar", year: 2014 },
        { id: 3, name: "Dunkirk", year: 2017 },
      ],
    }))
  },
})

export default function Home() {
  return (
    <div>
      <Link href="/posts">
        <a>Posts</a>
      </Link>
      <p>index page</p>
    </div>
  )
}
```

<img width="531" alt="Screen Shot 2020-10-03 at 21 03 24" src="https://user-images.githubusercontent.com/1720209/94991160-2359a480-05bc-11eb-8f32-d8d4d5dcfda1.png">

Does anyone knows about this?

**Comment by samselikoff** [comment]
Hm, is your app making any API requests?

**Comment by samselikoff** [comment]
You might want to throw a `passthrough()` in your `routes()` hook in case Next is making AJAX requests to fetch JS resources:

```js
new Server({
  routes() {
    this.get("/api/movies", () => ({
      movies: [
        { id: 1, name: "Inception", year: 2010 },
        { id: 2, name: "Interstellar", year: 2014 },
        { id: 3, name: "Dunkirk", year: 2017 },
      ],
    }))

    this.passthrough()
  },
})
```

**Comment by ynotdraw** [comment]
Hey @samselikoff

I actually just hit this as well.  It appears to be an issue when I migrated Next.js from `9.3.x` to `9.5.5`.  Here's the full error message mirage is throwing:

```
{
  "description": "Mirage: undefined",
  "message": "Mirage: Your app tried to GET '/_next/static/development/_devPagesManifest.json', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?",
  "name": "Error",
  "stack": "Mirage: Error: Your app tried to GET '/_next/static/development/_devPagesManifest.json', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?\n    at new MirageError (webpack-internal:///./node_modules/miragejs/dist/mirage-esm.js:806:13)\n    at assert (webpack-internal:///./node_modules/miragejs/dist/mirage-esm.js:791:11)\n    at Pretender.unhandledRequest (webpack-internal:///./node_modules/miragejs/dist/mirage-esm.js:7206:9)\n    at Pretender.handleRequest (webpack-internal:///./node_modules/pretender/dist/pretender.es.js:1505:22)\n    at FakeRequest.send (webpack-internal:///./node_modules/pretender/dist/pretender.es.js:1320:27)\n    at eval (webpack-internal:///./node_modules/pretender/dist/pretender.es.js:511:9)\n    at new Promise (<anonymous>)\n    at fetch (webpack-internal:///./node_modules/pretender/dist/pretender.es.js:448:10)\n    at PageLoader.getPageList (webpack-internal:///./node_modules/next/dist/client/page-loader.js:164:45)\n    at Router._callee4$ (webpack-internal:///./node_modules/next/dist/next-server/lib/router/router.js:1105:40)\n    at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:63:40)\n    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:293:22)\n    at Generator.eval [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:118:21)\n    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)\n    at new Promise (<anonymous>)\n    at Router.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)\n    at Router.prefetch (webpack-internal:///./node_modules/next/dist/next-server/lib/router/router.js:1135:26)\n    at Object.instance.<computed> [as prefetch] (webpack-internal:///./node_modules/next/dist/client/router.js:170:29)\n    at prefetch (webpack-internal:///./node_modules/next/dist/client/link.js:80:10)\n    at eval (webpack-internal:///./node_modules/next/dist/client/link.js:225:11)\n    at eval (webpack-internal:///./node_modules/next/dist/client/link.js:45:9)\n    at Array.forEach (<anonymous>)\n    at IntersectionObserver.rootMargin (webpack-internal:///./node_modules/next/dist/client/link.js:35:13)"
```

I've also created a small repo for reproduction at: https://github.com/ynotdraw/miragejs-next-runtime-error-reproduction

```bash
yarn
yarn dev
```

Should give you the error.

I've found that the error appears to be when you add a `<Link` element to a page, which seems pretty odd.  At any rate, as you can see, it's making a request to `/_next/static/development/_devPagesManifest.json` which is causing Next to blow up.  If you comment out the link at https://github.com/ynotdraw/miragejs-next-runtime-error-reproduction/blob/main/pages/index.js#L23, no complaints!

Additionally, I've found uncommenting: https://github.com/ynotdraw/miragejs-next-runtime-error-reproduction/blob/d49ae3956b83cd8b58ddb64ee86d780bb722a759/mirage.js#L24 seems to allow the passthrough to work as expected; however, a standard `this.passthrough()` still gave me the error, which I thought was weird. 

Hope this helps!

**Comment by arsnl** [comment]
Depending of how your routes are defined in your mock server, you gonna have to set the passthrough differently.

If don't use the [namespace](https://miragejs.com/api/classes/server/#namespace), you can use the global `passthrough()` at the end of all your routes or a specific `passthrough("/_next/static/development/_devPagesManifest.json")`.

If you are using the namespace, you gonna have to use the [solution](https://github.com/ynotdraw/miragejs-next-runtime-error-reproduction/blob/d49ae3956b83cd8b58ddb64ee86d780bb722a759/mirage.js#L24-L30) proposed by @ynotdraw since I think the call for `/_next/static/development/_devPagesManifest.json` gonna be resolved to `api/_next/static/development/_devPagesManifest.json` (if the namespace is `api`). So, the call for `GET /_next/static/development/_devPagesManifest.json` will not be filtered by the passthrough.

**Comment by haluvibe** [comment]
@arsnl workaround works, but it would be great if this could be fixed properly

**Comment by samselikoff** [comment]
Gotcha - thanks for digging into this @arsnl!

The passthrough API is indeed weird in that it inherits any previously set namespace, but you can actually rest it back to the empty string before calling passthrough() if you want it to work on the root of the current domain, like this:

```js
createServer({
  routes() {
    this.namespace = 'api';

    // handles GET requests to /api/movies
    this.get("/movies", () => ({
      movies: [
        { id: 1, name: "Inception", year: 2010 },
        { id: 2, name: "Interstellar", year: 2014 },
        { id: 3, name: "Dunkirk", year: 2017 },
      ],
    }))

    // resets the namespace to the root
    this.namespace = "" // or this.namespace = "/"
    this.passthrough() // now this will pass through everything not handled to the current domain (e.g. localhost:3000)
  },
})
```

I think the "real" solution here is to improve the passthrough/namespace API so it's clear how the prefix is applied.

**Comment by BroFox86** [comment]
Thank you! @samselikoff solution also helps when Next.js and Mirage.js work in production mode. Next.js routing doesn't work in this case and I don't even get any errors.

**Comment by marcelovani** [comment]
@samselikoff Your solution worked. This is not well documented.
