### ISSUE TITLE
Not able to embed records

### ISSUE THREAD

**Issue by ChrizzDF** [miragejs/miragejs#661]
Hi there,

I just want the product response to embed the brand model.
From the docs and issues I read through, I used `embed: true` in my `RestSerializer` config but it's anyway not embedding the brand model.

Please have a look at my really simple scenario: https://miragejs.com/repl/v1/604
Using v0.1.41

Did I just oversee something?!

Thanks in advance!!!

**Comment by samselikoff** [comment]
Yes, just need one more thing – the `include` prop to tell the resource _which_ of its relationships to include: https://miragejs.com/api/classes/serializer/#include

Check it out: https://miragejs.com/repl/v1/605

(This trips people up a lot 😕)

**Comment by ChrizzDF** [comment]
Oh dear...
I only knew `include` in regards to JSON API and side-loading models.

Thanks for your help and this great project of course! 🥳
