### ISSUE TITLE
Handling different Server Errors

### ISSUE THREAD

**Issue by Manimall** [miragejs/miragejs#663]
Hello!
I'm using Mirage JS - and i found that if i try to simulate Server Error - there still a response Object - attention - not an Error obj (as it is on real Fetch request).... 

```js
import { createServer, Model, Response } from 'miragejs';

export default function () {
  createServer({
    models: {
      result: Model,
    },

    seeds(server) {
      server.create('result', { currentPassword: '12' });
    },

    routes() {
      this.get('/api/change-password', (schema) => {
        return schema.results.all();
      });

      this.post('/api/change-password', (schema, request) => {
        const attrs = JSON.parse(request.requestBody);
        schema.results.create(attrs);
      });

      // Using the `Response` class to return a 500
      this.post('/api/change-password2', (schema, request) => {
        return new Response(403, { some: 'header' }, { error: ['Неверный пароль'] });
      });

      this.post('/api/change-password3', (schema, request) => {
        return new Response(404, { some: 'header' }, { errors: ['userError'] });
      });

      this.post('/api/change-password4', (schema, request) => {
        return new Response(500, { some: 'header' }, { errors: ['serverError'] });
      });
    },
  });
}
```

this is my  server.js

![2020-10-11_07-53-37](https://user-images.githubusercontent.com/2580719/95670675-0104ef80-0b97-11eb-8b80-87771e2b3b08.png)

So, it would be great to simulate it originally, not providing a Response than it's an Error.
Also, i looked at types and couldn't find class or interface for an Error obj.

**Comment by samselikoff** [comment]
Sorry you ran into this (and sorry for the delay in responding!)

I think the `fetch` API doesn't `throw` an actual JS exception if the server responds with a 400 or 500 response. Instead I think you need to inspect the `response` and check for `response.ok`:

```js
let response = await fetch('/api/change-password3', {
  method: 'POST',
  body: "..."
})

if (response.ok) {
  // success status code
} else {
  // should end up here if 400x or 500x response code
}
```

rather than try/catch. This is how it should work against a production server too.

**Comment by Manimall** [comment]
@samselikoff you're right!

https://codesandbox.io/s/exploring-fetch-superagent-responses-okf5q?file=/src/App.js

I thought Fetch and superAgent are both working the same way, but i was wrong(

so, in my case above i was working with SA - not Fetch and what's why i wrote this issue.

@samselikoff thank you for response!)

**Comment by samselikoff** [comment]
Awesome, and you're welcome – glad you got it working!
