### ISSUE TITLE
Auth0 usage with MirageJS

### ISSUE THREAD

**Issue by Magvin** [miragejs/miragejs#676]
Trying to mock a server with Graphql, the main flow is heavily relying on Auth0 authentication. As Auth0 uses cookies for storing information, Authentication flow isn't working on Graphql request, as cookies are cleared every single time.

Any known work around?

**Comment by samselikoff** [comment]
Hm I haven't done this myself, but have you seen the guide on simulating cookie responses?

https://miragejs.com/docs/advanced/simulating-cookie-responses/

When you say the cookies are cleared what do you mean? How are they being cleared?

**Comment by Magvin** [comment]
hi @samselikoff  thanks for answer.
Yes i have tried to simulate cookie reponses.
But as it seems new Auth0 SDK provider 
https://auth0.com/docs/quickstart/spa/react/01-login
stores they auth tokens in cookies as it's not safe to store in local storage.
So as soon i'm clicking Login (and i have mocked grapqhl server which does request to check if user exists in DB)
cookies from AUTH0 are gonna. 
Not sure why it's clearing them.

**Comment by samselikoff** [comment]
I see. 

Can you share a simplified repo that reproduces the issue? If so I’d be happy to take a closer look!

**Comment by Magvin** [comment]
![image](https://user-images.githubusercontent.com/23562296/96770422-4ff12700-13d8-11eb-9488-f3ac71116175.png)
so here is the image with cookies from Auth0. as soon i'm importing './server.js' this cookies will be gonna, and you will be not able to login. Below is the link to min version, but you will need to insert your AUTH0 credentials there in index.js

https://github.com/Magvin/miragejs-auth0notworking

**Comment by delucca** [comment]
Is this issue really closed? I'm facing the same issuer here.

As soon as I star the MirageJS server my Auth0Provider stops working.
