### ISSUE TITLE
TypeScript complains about the model type does not exist on the schema

### ISSUE THREAD

**Issue by haluvibe** [miragejs/miragejs#681]
duplicate of #460 but this was closed without an adequate resolution.

**Comment by MrSrsen** [comment]
I resolved this with solution from discussion in the merge request: https://github.com/miragejs/miragejs/pull/262/files/364ed6236a7dcdc8a5729ef9d55790c32f63221d#diff-1a4f1c00746aa0d97513ea9b18766df309ed4794cf832267d719ec1cf35a585cR121

> Property 'movies' does not exist on type 'Schema<Record...

and reply:

> schema.db.movies.find() works and using schema.db is in the documentation...
> https://miragejs.com/docs/main-concepts/orm#why-an-orm

**Comment by haluvibe** [comment]
What type is schema below then???

```
import { Server } from 'miragejs'
import Schema from 'miragejs/orm/schema'

export const setupTodosMirageRoutes = (server: Server) => {
  server.get('/todos', (schema) => {
    return schema.db.todos.all()
  })
```

**Comment by haluvibe** [comment]
perfect thx

**Comment by delucca** [comment]
> I resolved this with solution from discussion in the merge request: https://github.com/miragejs/miragejs/pull/262/files/364ed6236a7dcdc8a5729ef9d55790c32f63221d#diff-1a4f1c00746aa0d97513ea9b18766df309ed4794cf832267d719ec1cf35a585cR121
> 
> > Property 'movies' does not exist on type 'Schema<Record...
> 
> and reply:
> 
> > schema.db.movies.find() works and using schema.db is in the documentation...
> > https://miragejs.com/docs/main-concepts/orm#why-an-orm
> 
> So instead of:
> 
> ```js
> const movie = schema.movies.find(request.params.id);
> ```
> 
> use:
> 
> ```js
> const movie = schema.db.movies.find(request.params.id);
> ```

What about `all`? There is no `all` inside `db`

**Comment by delucca** [comment]
I've opened #703 since I don't think this issue is actually solved
