### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by popuguytheparrot** [miragejs/miragejs#693]
Hi.

Is it possible to add gRPC support?

**Comment by jvgreenaway** [comment]
This would be awesome if it is possible

**Comment by ftonato** [comment]
Is support for `gRPC` in this year's roadmap?

**Comment by IanVS** [comment]
Mirage is mostly unmaintained for now, so there's no real "roadmap" to speak of.  If it's something you require, I'd suggest forking and building it, and perhaps submitting a PR back.  

The main effort right now is being done by a contributor to split out pretender to allow usage with other libraries such as MSW.
