### ISSUE TITLE
Mocking GraphQL with @apollo/client

### ISSUE THREAD

**Issue by ygorlf** [miragejs/miragejs#704]
Hi, so in love with this amazing library! 💯 💯 

I'm trying to use in my current application with GraphQL. I'm a very happy user of apollo client and can't find a way to intercept the requests that my app does with it.

I made a setup using apollo and graphql-request, In the apollo example my request doesn't pass through miragejs but everything works great using the graphql-request.

I created 2 branchs to exemplify the behavior (apollo & graphql-request).

https://github.com/ygorlf/graphql-mock-example

Made a Codesandbox too:

apollo: https://codesandbox.io/s/mirage-apollo-on80f
graphql-request: https://codesandbox.io/s/graphql-request-c97ke

**Comment by joeboylson** [comment]
Hey @ygorlf, I was having the same issue but I think I found a way around it. I tried a few things and I found that:
1. you have to start the mirage mock server before setting up the Apollo client
2. the Apollo client has to use a relative url like `/graphql` rather than `http:example.com/graphql`

**Comment by ygorlf** [comment]
Hi @joeboylson, starting the miragejs server before the apollo client setup made the trick 👍 

I'll try the proxy alternative with relative url too. Thank you!!! 💯

**Comment by joeboylson** [comment]
@ygorlf Great to hear! Good luck on your project!

**Comment by ygorlf** [comment]
For those who may have trouble with that in the future this is my working solution:

I had to switch between the uri/link option on my Apollo instance to make it work, with the link options the miragejs doesn't intercept my requests but everything works setting the uri directly!

`
const applyMock = process.env.NODE_ENV === 'development' || window.Cypress;

if (applyMock) {
  mockedServer();
}

export const client = new ApolloClient({
  ...applyMock && {
    uri: 'https://my-api.com/graphql',
  },
  ...!applyMock && {
    link,
  },
  cache: new InMemoryCache({
    dataIdFromObject: o => (o._id ? `${o.__typename}:${o._id}` : null),
  }),
  defaultOptions: {
    query: {
      fetchPolicy: 'network-only',
    },
  },
});
`
