### ISSUE TITLE
RXJS & How does it work internally?

### ISSUE THREAD

**Issue by MaximeBernard** [miragejs/miragejs#735]
Hi there and thanks for this nice developer experience. 

I intended to use it on my project until I realized I couldn't 
```typescript 
import { ajax } from 'rxjs/ajax';

ajax.getJSON('/api/users').subcribe(users => console.log(users)); 
```
Did I miss something or is it by design?

Speaking of design, I tried to know more about this but the documentation doesn't quite explain how does it work internally (even though it does explain a lot of interesting stuff, good job on that). 

My intuition guess is that you override `window.fetch` and add your whole code around it. Am I close?

If that's the case, It seems a bit more difficult to handle `rxjs`. The only thing I could think of is using the same mechanism as `jest` (i.e. override imports).

**Comment by samselikoff** [comment]
Hm it should work, what Mirage code did you try? (i.e. where and how did you call `createServer()`?)

**Comment by MaximeBernard** [comment]
My bad! Trying to give you a repro, I made it work... 🤦 

I'd love to know more though on how did you manage to do that 🤩 

Great job so far 👍
