### ISSUE TITLE
Mock only certain routes?

### ISSUE THREAD

**Issue by matteogll** [miragejs/miragejs#755]
I'm using miragejs in Vue. 
It works well but it seems that **ALL** API calls need to be configured in server.js configuration file.
Is it possible to exclude certain routes to be mocked by Mirage? (For the excluded routes the Vue.js application should make the normal call using Axios/Fetch.

Here is a complete example (server.js):

```
import { createServer } from "miragejs";

export default function() {
    createServer({
        routes() {
            this.urlPrefix = "https://myApiServer1";
            this.namespace = "/api";
            this.get("/users/", () => [
                {
                    username: "user1"
                },
                {
                    username: "user2"
                },
            ]);
        },
    });
}
```
I would like to NOT mock all the API calls, for example, to  "https://myApiServer2"

**Comment by samselikoff** [comment]
Yes! Check out [the Passthrough docs](https://miragejs.com/docs/getting-started/overview/#passthrough).

You should be able to just call `this.passthrough()` at the end of your `routes()` hook if you want to ignore requests on the same domain.

**Comment by matteogll** [comment]
Thanks @samselikoff ,
it works!
The new configuration is:
```
export default function() {
    createServer({
        routes() {
            this.urlPrefix = "https://myApiServer1";
            this.namespace = "/api";
            this.get("/users/", () => [
                {
                    username: "user1"
                },
                {
                    username: "user2"
                },
            ]);
            this.passthrough("https://myApiServer2/**"); // important: specify domain if it's external 
        },
    });
}
```

**Comment by samselikoff** [comment]
Awesome!
