### ISSUE TITLE
How can I embed child data with many-to-many relationships?

### ISSUE THREAD

**Issue by kodaniel** [miragejs/miragejs#756]
I have two Models in MirageJs:
- blog
- tag

Each blog could have more tags and vice versa. I made a many-to-many relationship with a join table called `blog_tag`. My problem is, when I get the response from the server, the **tags** only contains the id properties. How could I embed the whole tag object into the response?

```json
Response:
{
  "blogs": [
    {
      "title": "Some title",
      "author": "Author 0",
      "id": "1",
      "tags": [
        {
          "id": "1"
          // Other properties are not included here :(
        }
      ]
    }
  ]
}

I'd like to see something like this:
{
  "blogs": [
    {
      "title": "Some title",
      "author": "Author 0",
      "id": "1",
      "tags": [
        {
          "id": "1",
          "name": "Tag 0"
        }
      ]
    }
  ]
}
```

My server config:
[Mirage REPL](https://miragejs.com/repl/v2/bf44f66f46)
```js
import { belongsTo, createServer, Factory, hasMany, Model, RestSerializer } from "miragejs"

export default createServer({
  serializers: {
    blog: RestSerializer.extend({
      include: ['tags'],
      embed: true
    })
  },

  models: {
    blog: Model.extend({
      tags: hasMany('blog_tag')
    }),

    tag: Model.extend({
      blogs: hasMany('blog_tag')
    }),

    blog_tag: Model.extend({
      blog: belongsTo(),
      tag: belongsTo()
    })
  },

  factories: {
    blog: Factory.extend({
      author(i) {
        return 'Author ' + i
      },
      title() {
        return 'Some title'
      }
    }),
    tag: Factory.extend({
      name(i) {
        return 'Tag ' + i
      }
    })
  },

  seeds(server) {
    server.createList('blog', 2)
    server.createList('tag', 10)

    server.create('blog_tag', { blogId: 1, tagId: 1 })
  },

  routes() {
    this.namespace = "api"

    this.get("/blogs", (schema) => {
      return schema.blogs.all()
    })
  },
})
```

**Comment by clementoriol** [comment]
I answered this on StackOverflow: https://stackoverflow.com/questions/65710036/how-can-i-embed-child-data-with-many-to-many-relationships/65737186#65737186 

I guess this could be closed ?

**Comment by kodaniel** [comment]
Yep, thanks.

**Comment by neilmispelaar** [comment]
May I just say thank you from the bottom of my heart for this creating this issue @kodaniel and for providing a solution @clementoriol . 

MirageJS is absolutely genius, though I've been struggling for two days with getting the response to shoot out a HasMany relationship. 

The sample REPL provided solved my problem in seconds, and now I can move on to other things. 

Thank you again.
