### ISSUE TITLE
this.normalizedRequestAttrs() normalizes any request attribute that exists in the models

### ISSUE THREAD

**Issue by SkoebaSteve** [miragejs/miragejs#761]
I'm trying to understand how `this.normalizedRequestAttrs()` works. 

I have a route handler for an existing model called `check`. I'm trying to mimic a 422 Response that returns if the request body does not contain `{ "check": {} }`. 

So I would do `let check = this.normalizedRequestAttrs()`

If I pass a request attribute that does not exist in 'any' model(for example `{ "pancake": {} }`, I get the following error: 

> message: "Mirage: Model not registered: pancake"

If I pass a request attribute that does correspond with another model, it 'passes'  and returns attributes for that model.

I was expecting that `this.normalizedRequestAttrs()` would either error if the attribute doesn't respond with the model or at least be empty. 

Ps. I can solve it by using `let { check } = JSON.parse(request.requestBody);` first but I was hoping to combine the two.

**Comment by samselikoff** [comment]
Yeah `normalizedRequestAttrs` is really just some sugar for parsing the body then running it through any `normalize()` function on your serializer. It's really meant to be used with a model. I suppose you could try/catch and if it throws that error, you know the attrs from the request body weren't valid. But I'd probably do what you're doing by just checking the raw requestBody.

Sorry about the delayed answer!

**Comment by SkoebaSteve** [comment]
Ok I understand, thanks for the response!

> Sorry about the delayed answer!

Same here 😅
