### ISSUE TITLE
how to use findBy() for nested properties?

### ISSUE THREAD

**Issue by mmilano** [miragejs/miragejs#772]
Behavior/usage question: 
I am attempting to use findBy to find a dB entry value is that a multi-level nested property.
I also have data models for entities that have multi-level properties, like the following illustration where date{} has multiple nested properties.

```js
aRecord: {
  id: 2,
  date: {
     created_by: userid,
     modified_by: userid
  }
}
```
In the case of user records, 
I am attempting to find a user by `username` (on signin) where the user data structure is like the following (reduced for brevity):
```js
{
  id: “1”,
  account: {
    username: “root”,
  }
},
{
  id: “2”,
  account: {
    username: “eric_praline”,
  }
}
```

using a route...
```js
     this.get("/users/", ({users}, request) => {
        let whichUser = request.queryParams.user;
        let queryAttr = {
            account: {
                username: whichUser,
            }
        };
        let user = users.findBy(queryAttr);
     ...
    }
```

and a request
```js 
    let findUser = await axios.get(`/api/users/?user=${username}`);
```

However, the first record (id=1) is always returned, suggesting that it is querying against the existence of the `account` property rather than the value of `username`.

Is there a correct way to findBy() nested record properties?

And how can Model extensions be created to add assoications to a nested property, such as in the `created_by` property exampled above?

**Comment by samselikoff** [comment]
Sorry for not responding, did you figure it out? Maybe `find(f)` with a function?

**Comment by mmilano** [comment]
thank you, no, i didn't figure out a solution. 

what would find(f) with a function be? perhaps i am not understanding something about the options i have available?

from looking into the core code, i saw how the fundamental find method is very flat,
but i wasnt clear how i could supply a custom queryFunction...

**Comment by bewards** [comment]
Also interested in a more robust find function that could allow us to do a more in depth query or comparison.

**Comment by JusticeBoi** [comment]
An alternative albeit uglier way to achieve it could be:

```js
const user = users.all().filter(user => { 
  return user.account.username === whichUser
}.models[0]
```

**Comment by angelocordon** [comment]
I stumbled into this issue while trying to figure this out myself. Posting here in case someone else is still wondering, it looks like we can pass in a query function in the `findBy` method and not just an object.

https://github.com/miragejs/miragejs/blob/master/lib/db-collection.js#L387-L388

So it's possible to do something like:
```js
users.findBy(user => user.account.username === whichUser)
```

**Comment by cah-brian-gantzler** [comment]
Thanks for letting people know. Hope someone does a PR to update the docs. If you drill into the findBy you will eventually find that is does check, if its not an object, assumes its a function.   https://github.com/miragejs/miragejs/blob/master/lib/db-collection.js#L387
