### ISSUE TITLE
'underscore' is not exported from miragejs

### ISSUE THREAD

**Issue by geochronology** [miragejs/miragejs#798]
I'm following the documentation on how to use underscores for my serializer, and here's what it says:

(From https://miragejs.com/api/classes/serializer/#key-for-relationship)
Overwrite keyForRelationship to format this key:

```
// serializers/application.js
export default Serializer.extend({
  keyForRelationship(modelName) {
    return underscore(modelName);
  }
});
```

A certain `underscore` method is referenced here, but I can't find any supporting documentation to show where this method is coming from, or what it would look like. It's also not exported from miragejs itself.

Am I missing something? Can someone help me figure out how to make mirage leave my underscores alone?

**Comment by geochronology** [comment]
Alright, a bit of digging points me to `underscore` being an export from [@ember/string](https://api.emberjs.com/ember/release/classes/String/methods/loc?anchor=underscore). 

Which would be great, but I'm using React! No ember string for me ;-;

I've recreated the `underscore` method here using a simplified version of the [Ember source code](https://github.com/emberjs/ember.js/blob/v2.12.2/packages/ember-runtime/lib/system/string.js#L277).

```
export const underscore = str => {

  const regex1 = (/([a-z\d])([A-Z]+)/g)
  const regex2 = (/\-|\s+/g)

  return str.replace(regex1, '$1_$2')
    .replace(regex2, '_')
    .toLowerCase()

}

```

May I thus suggest adding this `underscore` method to miragejs itself? I think it would be quite handy for all of us using the MirageJS serializer who aren't on Ember and don't have access to this method natively.

**Comment by samselikoff** [comment]
I agree that the guides example is incomplete! Maybe we change it to include showing `import { snakeCase } from lodash` and using that instead?

I don't think we should add one to miragejs directly
