### ISSUE TITLE
Ion-icon not working

### ISSUE THREAD

**Issue by pawangujral** [miragejs/miragejs#813]
First of all thanks for this awesome lib.
However, Using Miragejs for my Ionic React project I'm facing one issue. Hoping someone can help me as I couldn't find solution online(google/etc).

Add icon
`<IonIcon icon={map} />`

uncaught promise error
`"Mirage: Your app tried to GET 'data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' class='ionicon' viewBox='0 0 512 512'><title>Map</title><path d='M48.17 113.34A32 32 0 0032 141.24V438a32 32 0 0047 28.37c.43-.23.85-.47 1.26-.74l84.14-55.05a8 8 0 003.63-6.72V46.45a8 8 0 00-12.51-6.63zM212.36 39.31A8 8 0 00200 46v357.56a8 8 0 003.63 6.72l96 62.42A8 8 0 00312 466V108.67a8 8 0 00-3.64-6.73zM464.53 46.47a31.64 31.64 0 00-31.5-.88 12.07 12.07 0 00-1.25.74l-84.15 55a8 8 0 00-3.63 6.72v357.46a8 8 0 0012.52 6.63l107.07-73.46a32 32 0 0016.41-28v-296a32.76 32.76 0 00-15.47-28.21z'/></svg>', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?"`

My server.js
`  routes() {
    this.namespace = "/api";

    this.get("/events", (schema: any, request) => {
      return schema.events.all();
    });

    this.passthrough();

  },`

I tried all solution mentioned online. However no luck.

![Screenshot 2021-03-04 at 5 37 13 PM](https://user-images.githubusercontent.com/20306080/109961695-4970a580-7d10-11eb-8486-871e486eae5d.png)

**Comment by samselikoff** [comment]
I think there was a PR addressing this a while back https://github.com/miragejs/miragejs/pull/431

Could you see if that code works for you? Also, if it does, you might be the best person to push that PR forward since you're running into this problem right now!

**Comment by pawangujral** [comment]
thanks @samselikoff Yes that solution worked.

`  
 this.pretender.unhandledRequest = (verb, path, request: any) => {
        if (!request.url.indexOf("data:")) {  
          request.passthrough();
        } else {
          path = decodeURI(path);
          assert(
            `Your app tried to ${verb} '${path}', but there was no route defined to handle this request. Define a route for this endpoint in your routes() config. Did you forget to define a namespace?`
          );
        }
      }
`
