### ISSUE TITLE
Limited Typing Exposure of Collection

### ISSUE THREAD

**Issue by nbibler** [miragejs/miragejs#832]
The [Collection class](https://github.com/miragejs/miragejs/blob/b965b8a058523dac0d6ab4792826887154e25368/lib/orm/collection.js) seems to have several useful public methods exposed (like `includes`, `filter`, `sort`, `slice`, …) that aren't currently identified in the TypeScript typings:

https://github.com/miragejs/miragejs/blob/b965b8a058523dac0d6ab4792826887154e25368/types/index.d.ts#L87-L94

Is it intentional that these Array-like utility methods are hidden from the typings? Are they not intended to be utilized outside of the package?

**Comment by samselikoff** [comment]
Nope not intentional! I don't maintain the types so it looks like they're just incomplete. Feel free to add them!

**Comment by nbibler** [comment]
Sounds good, I'll get a PR up later tonight. Just wanted to check before putting in the effort. 😁

**Comment by nbibler** [comment]
I've opened PR #833 to add the missing method signatures. Closing this issue and delegating to the PR.
