### ISSUE TITLE
Miragejs Pagination support

### ISSUE THREAD

**Issue by aadamsx** [miragejs/miragejs#838]
Does Miragejs support Pagination mocking APIs?  If so, is there a good example somewhere?

**Comment by acorncom** [comment]
@aadamsx looks like you asked this before? 😉 https://github.com/miragejs/miragejs/issues/551

**Comment by aadamsx** [comment]
Yes, but it's been a year so i thought maybe it could have been added.  But honestly I don't see how we can properly mock an API that has pagination without this support.

**Comment by acorncom** [comment]
@aadamsx I found your question because I was checking to see what my options were in a client project. If you take a look at https://miragejs.com/docs/main-concepts/route-handlers/#serialize, you're able to handle pagination as you see fit using that and slices of your model collections
