### ISSUE TITLE
Embedding Some Relationships, but Not All

### ISSUE THREAD

**Issue by alexlafroscia** [miragejs/miragejs#841]
Is it possible to embed _some_ of the relationships, but not _all_ of them?

It seems like the `embed` serializer is an all-or-nothing type of deal, without allowing for some relationships to be embedded and others to be "normal". Weird as that requirement might be, it's a situation we're running into right now!

**Comment by samselikoff** [comment]
I don't think so atm :/ Here's the logic currently:

https://github.com/miragejs/miragejs/blob/master/lib/serializer.js#L691-L696

Best bet would probably be to override one of those methods in your own app. Or work on a PR If you feel so inclined!

**Comment by alexlafroscia** [comment]
Gotcha -- that's what I thought, but I wanted to make sure I wasn't missing something first!

If it comes to making a PR, would an API like this work for you?

```js
Serializer.extend({
  // Never embed a relationship
  embed: false
});

Serializer.extend({
  // Always embed every relationship
  embed: true
});

Serializer.extend({
  // Embed just the listed relationships
  embed: ['child']
});
```

Another thought would be do to something with a function that is called for each relationship to see if it's embedded or not, but that probably doesn't make much sense since that API would diverge from the current one, rather than extending it.

**Comment by samselikoff** [comment]
I was thinking function too. What do you mean by diverge from the current one?

**Comment by alexlafroscia** [comment]
For example, if the current API is `embed: true` or `embed: false`, `embed: [...RELATIONSHIPS]` sort of feels like an "extension" of the current API.

I guess now that I'm thinking about it, `embed` as a function that works similar to `included` doesn't feel _that_ different. I was at first imagining something like the `keyFor___` hooks that are called multiple times, but designing it to be like `included` probably makes the most sense.

Would that be the better direction, then?

**Comment by samselikoff** [comment]
Yep I think function is best direction 👍  If I were starting over today that would probably be the "base" type since it's the most flexible. Don't think it's a problem that it adds a new possible type for the value!

**Comment by alexlafroscia** [comment]
Absolutely! Making every configuration option able to be defined as a function -- or even better, an async function -- just adds _so_ much flexibility. Definitely the way to go!
